### ISSUE TITLE
"Invalid addition: write + write-read" error

### ISSUE THREAD

**Issue by fpoli** [viperproject/prusti-dev#105]
The following program causes an internal error in Prusti.

```rust
use prusti_contracts::*;

#[derive(Copy, Clone)]
struct State;

impl PartialEq for State {
    #[trusted]
    fn eq(&self, other: &State) -> bool {
        unimplemented!();
    }
}

fn worker_handoff(curr: State) -> State {
    let mut curr: State = curr;
    loop {
        let actual = curr;
        if actual == curr {
            return curr;
        }
    }
}

fn main(){}

```

```
thread 'main' panicked at 'internal error: entered unreachable code: Invalid addition: write + write-read', prusti-common/src/vir/ast/common.rs:103:18
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:515
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   7: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:413
   8: <prusti_common::vir::ast::common::PermAmount as core::ops::arith::Add>::add
   9: prusti_viper::encoder::foldunfold::state::State::insert_pred
  10: prusti_viper::encoder::foldunfold::state::State::insert_perm
  11: prusti_viper::encoder::foldunfold::state::State::insert_all_perms
  12: <prusti_common::vir::ast::stmt::Stmt as prusti_viper::encoder::foldunfold::semantics::ApplyOnState>::apply_on_state
  13: prusti_viper::encoder::foldunfold::FoldUnfold::restore_write_permissions
  14: prusti_viper::encoder::foldunfold::FoldUnfold::process_expire_borrows
  15: <prusti_viper::encoder::foldunfold::FoldUnfold<'p, 'v, 'r, 'a, 'tcx> as prusti_common::vir::cfg::visitor::CfgReplacer<prusti_viper::encoder::foldunfold::path_ctxt::PathCtxt<'p>, prusti_viper::encoder::foldunfold::ActionVec>>::replace_stmt
  16: prusti_viper::encoder::foldunfold::add_fold_unfold
  17: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode
  18: prusti_viper::encoder::encoder::Encoder::encode_procedure
  19: prusti_viper::encoder::encoder::Encoder::process_encoding_queue
  20: prusti_viper::verifier::Verifier::verify
  21: prusti::verifier::verify
  22: <prusti::compiler_calls::PrustiCompilerCalls as rustc_driver::CompilerCalls<'a>>::build_controller::{{closure}}
  23: rustc::ty::context::tls::with_context
  24: rustc_driver::driver::compile_input::{{closure}}
  25: rustc::ty::context::tls::enter_context
  26: <std::thread::local::LocalKey<T>>::with
  27: rustc::ty::context::TyCtxt::create_and_enter
  28: rustc_driver::driver::compile_input
  29: rustc_driver::run_compiler_with_pool
  30: <scoped_tls::ScopedKey<T>>::set
  31: syntax::with_globals
  32: rustc_driver::run_compiler
  33: prusti::prusti_runner::run_prusti
  34: prusti::driver_utils::monitor::{{closure}}
  35: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  36: rustc_driver::in_rustc_thread
  37: prusti::driver_utils::run
  38: prusti_driver::main
  39: std::rt::lang_start::{{closure}}
  40: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  41: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  42: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  43: main
  44: __libc_start_main
  45: _start
query stack during panic:
end of query stack
```

We should
- [ ] generate an internal error without crashing
- [ ] fix the internal error

**Comment by fpoli** [comment]
The example now works fine.
