### ISSUE TITLE
Labeling a function with a loop as #[pure] leads to a compiler error

### ISSUE THREAD

**Issue by Ramla-I** [viperproject/prusti-dev#1113]
I've used the linked_list code provided in the user guide and added one function that simply loops through the lists and returns false if the element passed to the function is equal to any in the list.
```
    pub fn no_overlap(&self, elem: i32) -> bool {
        let len = self.len();
        let mut i = 0;

        while i < len {
            body_invariant!(i < len);
            body_invariant!(i >= 0);
            if self.lookup(i) == elem {
                return false;
            }
            i += 1;
        }
        return true;
    }
```
This verifies without the #[pure] flag but leads to a compiler error with it. I'm just confused about why that would happen since this is technically a function without side effects.

The prusti assistant output is:
```
Run verification on /home/ramla/Desktop/linked_list/src/lib.rs...
Preparing verification run #34.
Killing 0 processes.
Run command '/home/ramla/.config/Code/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/cargo-prusti --message-format=json'
Spawned PID: 6867
Output from '/home/ramla/.config/Code/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/cargo-prusti --message-format=json' (0.5s):
┌──── Begin stdout ────┐
{"reason":"compiler-message","package_id":"linked_list 0.1.0 (path+file:///home/ramla/Desktop/linked_list)","manifest_path":"/home/ramla/Desktop/linked_list/Cargo.toml","target":{"kind":["lib"],"crate_types":["lib"],"name":"linked_list","src_path":"/home/ramla/Desktop/linked_list/src/lib.rs","edition":"2021","doc":true,"doctest":true,"test":true},"message":{"rendered":"warning: unused variable: `node`\n   --> src/lib.rs:150:28\n    |\n150 |             Link::More(box node) => false,\n    |                            ^^^^ help: if this is intentional, prefix it with an underscore: `_node`\n    |\n    = note: `#[warn(unused_variables)]` on by default\n\n","children":[{"children":[],"code":null,"level":"note","message":"`#[warn(unused_variables)]` on by default","rendered":null,"spans":[]},{"children":[],"code":null,"level":"help","message":"if this is intentional, prefix it with an underscore","rendered":null,"spans":[{"byte_end":3406,"byte_start":3402,"column_end":32,"column_start":28,"expansion":null,"file_name":"src/lib.rs","is_primary":true,"label":null,"line_end":150,"line_start":150,"suggested_replacement":"_node","suggestion_applicability":"MachineApplicable","text":[{"highlight_end":32,"highlight_start":28,"text":"            Link::More(box node) => false,"}]}]}],"code":{"code":"unused_variables","explanation":null},"level":"warning","message":"unused variable: `node`","spans":[{"byte_end":3406,"byte_start":3402,"column_end":32,"column_start":28,"expansion":null,"file_name":"src/lib.rs","is_primary":true,"label":null,"line_end":150,"line_start":150,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":32,"highlight_start":28,"text":"            Link::More(box node) => false,"}]}]}}
{"reason":"compiler-message","package_id":"linked_list 0.1.0 (path+file:///home/ramla/Desktop/linked_list)","manifest_path":"/home/ramla/Desktop/linked_list/Cargo.toml","target":{"kind":["lib"],"crate_types":["lib"],"name":"linked_list","src_path":"/home/ramla/Desktop/linked_list/src/lib.rs","edition":"2021","doc":true,"doctest":true,"test":true},"message":{"rendered":"warning: comparison is useless due to type limits\n  --> src/lib.rs:57:30\n   |\n57 | #[ensures(forall(|i: usize| (0 <= i && i < result.len()) ==> \n   |                              ^^^^^^\n   |\n   = note: `#[warn(unused_comparisons)]` on by default\n\n","children":[{"children":[],"code":null,"level":"note","message":"`#[warn(unused_comparisons)]` on by default","rendered":null,"spans":[]}],"code":{"code":"unused_comparisons","explanation":null},"level":"warning","message":"comparison is useless due to type limits","spans":[{"byte_end":917,"byte_start":911,"column_end":36,"column_start":30,"expansion":null,"file_name":"src/lib.rs","is_primary":true,"label":null,"line_end":57,"line_start":57,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":36,"highlight_start":30,"text":"#[ensures(forall(|i: usize| (0 <= i && i < result.len()) ==> "}]}]}}
{"reason":"compiler-message","package_id":"linked_list 0.1.0 (path+file:///home/ramla/Desktop/linked_list)","manifest_path":"/home/ramla/Desktop/linked_list/Cargo.toml","target":{"kind":["lib"],"crate_types":["lib"],"name":"linked_list","src_path":"/home/ramla/Desktop/linked_list/src/lib.rs","edition":"2021","doc":true,"doctest":true,"test":true},"message":{"rendered":"warning: comparison is useless due to type limits\n  --> src/lib.rs:72:16\n   |\n72 |     #[requires(0 <= index && index < self.len())]\n   |                ^^^^^^^^^^\n\n","children":[],"code":{"code":"unused_comparisons","explanation":null},"level":"warning","message":"comparison is useless due to type limits","spans":[{"byte_end":1211,"byte_start":1201,"column_end":26,"column_start":16,"expansion":null,"file_name":"src/lib.rs","is_primary":true,"label":null,"line_end":72,"line_start":72,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":26,"highlight_start":16,"text":"    #[requires(0 <= index && index < self.len())]"}]}]}}
{"reason":"compiler-message","package_id":"linked_list 0.1.0 (path+file:///home/ramla/Desktop/linked_list)","manifest_path":"/home/ramla/Desktop/linked_list/Cargo.toml","target":{"kind":["lib"],"crate_types":["lib"],"name":"linked_list","src_path":"/home/ramla/Desktop/linked_list/src/lib.rs","edition":"2021","doc":true,"doctest":true,"test":true},"message":{"rendered":"warning: comparison is useless due to type limits\n   --> src/lib.rs:103:24\n    |\n103 |     forall(|i: usize| (0 <= i && i < self.len()) ==>\n    |                        ^^^^^^\n\n","children":[],"code":{"code":"unused_comparisons","explanation":null},"level":"warning","message":"comparison is useless due to type limits","spans":[{"byte_end":2259,"byte_start":2253,"column_end":30,"column_start":24,"expansion":null,"file_name":"src/lib.rs","is_primary":true,"label":null,"line_end":103,"line_start":103,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":30,"highlight_start":24,"text":"    forall(|i: usize| (0 <= i && i < self.len()) ==>"}]}]}}
{"reason":"compiler-message","package_id":"linked_list 0.1.0 (path+file:///home/ramla/Desktop/linked_list)","manifest_path":"/home/ramla/Desktop/linked_list/Cargo.toml","target":{"kind":["lib"],"crate_types":["lib"],"name":"linked_list","src_path":"/home/ramla/Desktop/linked_list/src/lib.rs","edition":"2021","doc":true,"doctest":true,"test":true},"message":{"rendered":"warning: comparison is useless due to type limits\n   --> src/lib.rs:124:29\n    |\n124 |             body_invariant!(i >= 0);\n    |                             ^^^^^^\n\n","children":[],"code":{"code":"unused_comparisons","explanation":null},"level":"warning","message":"comparison is useless due to type limits","spans":[{"byte_end":2874,"byte_start":2868,"column_end":35,"column_start":29,"expansion":null,"file_name":"src/lib.rs","is_primary":true,"label":null,"line_end":124,"line_start":124,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":35,"highlight_start":29,"text":"            body_invariant!(i >= 0);"}]}]}}
{"reason":"compiler-message","package_id":"linked_list 0.1.0 (path+file:///home/ramla/Desktop/linked_list)","manifest_path":"/home/ramla/Desktop/linked_list/Cargo.toml","target":{"kind":["lib"],"crate_types":["lib"],"name":"linked_list","src_path":"/home/ramla/Desktop/linked_list/src/lib.rs","edition":"2021","doc":true,"doctest":true,"test":true},"message":{"rendered":"warning: comparison is useless due to type limits\n   --> src/lib.rs:138:15\n    |\n138 |     #[ensures(result >= 0)]\n    |               ^^^^^^^^^^^\n\n","children":[],"code":{"code":"unused_comparisons","explanation":null},"level":"warning","message":"comparison is useless due to type limits","spans":[{"byte_end":3119,"byte_start":3108,"column_end":26,"column_start":15,"expansion":null,"file_name":"src/lib.rs","is_primary":true,"label":null,"line_end":138,"line_start":138,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":26,"highlight_start":15,"text":"    #[ensures(result >= 0)]"}]}]}}
{"reason":"compiler-message","package_id":"linked_list 0.1.0 (path+file:///home/ramla/Desktop/linked_list)","manifest_path":"/home/ramla/Desktop/linked_list/Cargo.toml","target":{"kind":["lib"],"crate_types":["lib"],"name":"linked_list","src_path":"/home/ramla/Desktop/linked_list/src/lib.rs","edition":"2021","doc":true,"doctest":true,"test":true},"message":{"rendered":"warning: comparison is useless due to type limits\n   --> src/lib.rs:155:16\n    |\n155 |     #[requires(0 <= index && index < self.len())]\n    |                ^^^^^^^^^^\n\n","children":[],"code":{"code":"unused_comparisons","explanation":null},"level":"warning","message":"comparison is useless due to type limits","spans":[{"byte_end":3472,"byte_start":3462,"column_end":26,"column_start":16,"expansion":null,"file_name":"src/lib.rs","is_primary":true,"label":null,"line_end":155,"line_start":155,"suggested_replacement":null,"suggestion_applicability":null,"text":[{"highlight_end":26,"highlight_start":16,"text":"    #[requires(0 <= index && index < self.len())]"}]}]}}
{"reason":"compiler-message","package_id":"linked_list 0.1.0 (path+file:///home/ramla/Desktop/linked_list)","manifest_path":"/home/ramla/Desktop/linked_list/Cargo.toml","target":{"kind":["lib"],"crate_types":["lib"],"name":"linked_list","src_path":"/home/ramla/Desktop/linked_list/src/lib.rs","edition":"2021","doc":true,"doctest":true,"test":true},"message":{"rendered":"warning: 7 warnings emitted\n\n","children":[],"code":null,"level":"warning","message":"7 warnings emitted","spans":[]}}
{"reason":"build-finished","success":false}

└──── End stdout ──────┘
┌──── Begin stderr ────┐
    Checking linked_list v0.1.0 (/home/ramla/Desktop/linked_list)
[2022-08-02T02:03:57Z INFO  prusti_driver] Prusti version: commit 4dfd34d 2021-11-22 16:35:31 UTC, built on 2021-11-22 16:40:49 UTC
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier] Received 13 functions to be verified:
[2022-08-02T02:03:57Z INFO  prusti_common::stopwatch::log_level] [prusti-viper] Starting: encoding to Viper
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]  - TrustedOption::is_none (linked_list::{impl#0}::is_none)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]    Source: src/lib.rs:16:5: 16:34 (#0)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]  - TrustedOption::is_some (linked_list::{impl#0}::is_some)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]    Source: src/lib.rs:24:5: 24:34 (#0)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]  - TrustedOption::peek (linked_list::{impl#0}::peek)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]    Source: src/lib.rs:30:5: 30:30 (#0)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]  - replace (linked_list::replace)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]    Source: src/lib.rs:59:1: 59:47 (#0)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]  - List::len (linked_list::{impl#1}::len)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]    Source: src/lib.rs:67:5: 67:31 (#0)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]  - List::lookup (linked_list::{impl#1}::lookup)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]    Source: src/lib.rs:73:5: 73:46 (#0)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]  - List::new (linked_list::{impl#1}::new)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]    Source: src/lib.rs:78:5: 78:25 (#0)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]  - List::push (linked_list::{impl#1}::push)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]    Source: src/lib.rs:88:5: 88:38 (#0)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]  - List::pop (linked_list::{impl#1}::pop)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]    Source: src/lib.rs:105:5: 105:43 (#0)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]  - List::no_overlap (linked_list::{impl#1}::no_overlap)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]    Source: src/lib.rs:118:5: 118:48 (#0)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]  - Link::len (linked_list::{impl#2}::len)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]    Source: src/lib.rs:139:5: 139:27 (#0)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]  - Link::is_empty (linked_list::{impl#2}::is_empty)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]    Source: src/lib.rs:147:5: 147:31 (#0)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]  - Link::lookup (linked_list::{impl#2}::lookup)
[2022-08-02T02:03:57Z INFO  prusti_viper::verifier]    Source: src/lib.rs:156:5: 156:46 (#0)
[2022-08-02T02:03:57Z INFO  prusti_viper::encoder::encoder] Encoding: TrustedOption::is_none (linked_list::{impl#0}::is_none)
[2022-08-02T02:03:57Z INFO  prusti_viper::encoder::encoder] Encoding: TrustedOption::is_some (linked_list::{impl#0}::is_some)
[2022-08-02T02:03:57Z INFO  prusti_viper::encoder::encoder] Encoding: TrustedOption::peek (linked_list::{impl#0}::peek)
[2022-08-02T02:03:57Z INFO  prusti_viper::encoder::encoder] Encoding: replace (linked_list::replace)
[2022-08-02T02:03:57Z INFO  prusti_viper::encoder::encoder] Encoding: List::len (linked_list::{impl#1}::len)
[2022-08-02T02:03:57Z INFO  prusti_viper::encoder::encoder] Encoding: List::lookup (linked_list::{impl#1}::lookup)
[2022-08-02T02:03:57Z INFO  prusti_viper::encoder::encoder] Encoding: List::new (linked_list::{impl#1}::new)
[2022-08-02T02:03:57Z INFO  prusti_viper::encoder::encoder] Encoding: List::push (linked_list::{impl#1}::push)
[2022-08-02T02:03:57Z INFO  prusti_viper::encoder::encoder] Encoding: List::pop (linked_list::{impl#1}::pop)
[2022-08-02T02:03:57Z INFO  prusti_viper::encoder::encoder] Encoding: List::no_overlap (linked_list::{impl#1}::no_overlap)
thread 'rustc' panicked at 'Procedure DefId(0:85 ~ linked_list[efb9]::{impl#1}::no_overlap) contains a loop', prusti-viper/src/encoder/mir/pure/pure_functions/encoder.rs:100:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/core/src/panicking.rs:106:14
   2: prusti_viper::encoder::mir::pure::pure_functions::encoder::PureFunctionEncoder::encode_function
   3: <prusti_viper::encoder::encoder::Encoder as prusti_viper::encoder::mir::pure::pure_functions::interface::PureFunctionEncoderInterface>::encode_pure_function_def
   4: prusti_viper::encoder::encoder::Encoder::process_encoding_queue
   5: prusti_viper::verifier::Verifier::verify
   6: prusti_driver::verifier::verify
   7: rustc_interface::passes::QueryContext::enter
   8: <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis
   9: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  10: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  11: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>
  12: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new

note: Prusti version: commit 4dfd34d 2021-11-22 16:35:31 UTC, built on 2021-11-22 16:40:49 UTC

query stack during panic:
end of query stack
[2022-08-02T02:03:57Z INFO  prusti_common::stopwatch::log_level] [prusti-viper] Completed: encoding to Viper (0.126 seconds)
error: could not compile `linked_list`; 8 warnings emitted

└──── End stderr ──────┘
Exit code 101, signal null.
Ignored diagnostic message: '7 warnings emitted'
Prusti encountered an unexpected error.
Prusti encountered an unexpected error. We would appreciate a [bug report](https://github.com/viperproject/prusti-dev/issues/new). See the log (View -> Output -> Prusti Assistant) for more details.
Rendering 7 diagnostics at file:///home/ramla/Desktop/linked_list/src/lib.rs
```

**Comment by Aurel300** [comment]
Currently, `#[pure]` functions do not support loops. I think we know how to solve this, but it is not trivial. For the time being, your best bet is to try to rewrite such pure functions into recursive versions.

**Comment by Ramla-I** [comment]
thanks! that worked for me.
