### ISSUE TITLE
Consider using fs-err for prusti-rustc

### ISSUE THREAD

**Issue by vakaras** [viperproject/prusti-dev#245]
Currently, if we get a missing file error from `prusti-rustc`, it is not actionable:

```
thread 'main' panicked at 'called Result::unwrap() on an Err value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
```

(Taken from [here](https://prusti.zulipchat.com/#narrow/stream/236614-general/topic/Prusti.20CLI).)

A simple improvement would be to switch to [fs-err](https://crates.io/crates/fs-err) that has much better error messages.

cc @fpoli

**Comment by vcm-at-dfinity** [comment]
This is the file I attempted to verify (I was expecting the verification to fail)
```rust
extern crate prusti_contracts;

#[pure]
#[ensures="result >= a && result >= b"]
#[ensures="result == a || result == b"]
fn max(a: i32, b: i32) -> i32 {
    if a < b {
        b
    } else {
        a + 1
    }
}

fn main() {
  
}
```


And this is the stack trace:
```
victor:~/tmp/prusti$ prusti-rustc ../first-rust/src/main.rs
  __          __        __  ___             
 |__)  _\/_  |__) |  | /__`  |   ____\/_  | 
 |      /\   |  \ \__/ .__/  |       /\   | 

Commit hash: c9a44071fea897a2046
Commit time: 2020-07-27 11:09:14 UTC
Build time: 2020-07-27 13:52:45 UTC

warning: function is never used: `max`
 --> ../first-rust/src/main.rs:6:1
  |
6 | fn max(a: i32, b: i32) -> i32 {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

Verification of 2 items...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:515
   6: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   7: rust_begin_unwind
             at libstd/panicking.rs:337
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   9: core::result::unwrap_failed
  10: viper::viper::Viper::new_with_args
  11: prusti_common::verification_context::VerifierBuilder::new
  12: prusti_viper::verifier::Verifier::verify
  13: prusti::verifier::verify
  14: <prusti::compiler_calls::PrustiCompilerCalls as rustc_driver::CompilerCalls<'a>>::build_controller::{{closure}}
  15: rustc::ty::context::tls::with_context
  16: rustc_driver::driver::compile_input::{{closure}}
  17: rustc::ty::context::tls::enter_context
  18: <std::thread::local::LocalKey<T>>::with
  19: rustc::ty::context::TyCtxt::create_and_enter
  20: rustc_driver::driver::compile_input
  21: rustc_driver::run_compiler_with_pool
  22: <scoped_tls::ScopedKey<T>>::set
  23: syntax::with_globals
  24: rustc_driver::run_compiler
  25: prusti::prusti_runner::run_prusti
  26: prusti::driver_utils::monitor::{{closure}}
  27: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  28: prusti::driver_utils::run
  29: prusti_driver::main
  30: std::rt::lang_start::{{closure}}
  31: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  32: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  33: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  34: main
  35: __libc_start_main
  36: _start
query stack during panic:
end of query stack

note: the compiler or Prusti unexpectedly panicked.
note: possible reasons include the usage of Rust features that are not supported by Prusti.
note: we would appreciate a bug report for Prusti: <https://github.com/viperproject/prusti-dev/issues>
note: Prusti hash c9a44071fea897a2046 (2020-07-27 11:09:14 UTC) built on 2020-07-27 13:52:45 UTC
note: rustc <unknown> running on x86_64-unknown-linux-gnu
```

**Comment by fpoli** [comment]
The reason is that the release v-2020-07-27-1200 still requires to manually set a bunch of environment variables.

The environment variables are:
* `VIPER_HOME` should point to the folder containing all the `.jar` files
* `Z3_EXE` should point to the `z3` executable
* `JAVA_HOME` should point to the home folder of Java

These variables are no longer needed if you wish to try the latest pre-release from Github.

**Comment by fpoli** [comment]
Anyway, we should include at least a README in the zip of that release to explain how to make the binaries executable and how to set the environment variables.

**Comment by vcm-at-dfinity** [comment]
That fixed it, thank you! 

On your defense, now that you mention it, I remember seeing something about these environment variables somewhere in the tutorial; I could have double checked. Thanks for the assistance! :+1: 

I will download the latest pre-relase and try later, thanks.
