### ISSUE TITLE
ICE unexpected panic failed generation of folding/unfolding 

### ISSUE THREAD

**Issue by tillarnold** [viperproject/prusti-dev#264]
@vakaras  @cmatheja: Verifying the following program fails with `thread 'rustc' panicked at 'failed generation of folding/unfolding in DefId(0:10 ~ sum_compile_error2[317d]::{impl#0}::sum)', prusti-viper/src/encoder/pure_function_encoder.rs:274:14`

```rust
#![allow(dead_code, non_snake_case)]
use prusti_contracts::*;

struct T {
    f: u32,
}

impl T {
    #[pure]
    #[ensures( result == (self.f * (self.f + 1)) /2)]
    fn sum(&self) -> u32 {
        if self.f == 0 {
            0
        } else {
            self.f + (T { f: self.f - 1 }.sum())
        }
    }
}

fn main() {}
```

<details>
  <summary>stack backtrace</summary>
  
  ```
thread 'rustc' panicked at 'failed generation of folding/unfolding in DefId(0:10 ~ sum_compile_error2[317d]::{impl#0}::sum)', prusti-viper/src/encoder/pure_function_encoder.rs:274:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/98d66340d6e63eda115afc8b0da1d87965881936/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/98d66340d6e63eda115afc8b0da1d87965881936/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/98d66340d6e63eda115afc8b0da1d87965881936/library/core/src/option.rs:1260:5
   3: core::option::Option<T>::expect
             at /home/till/.rustup/toolchains/nightly-2020-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   4: prusti_viper::encoder::pure_function_encoder::PureFunctionEncoder::encode_function_given_body
             at ./prusti-viper/src/encoder/pure_function_encoder.rs:269:13
   5: prusti_viper::encoder::pure_function_encoder::PureFunctionEncoder::encode_function
             at ./prusti-viper/src/encoder/pure_function_encoder.rs:124:13
   6: prusti_viper::encoder::encoder::Encoder::encode_pure_function_def
             at ./prusti-viper/src/encoder/encoder.rs:1223:37
   7: prusti_viper::encoder::encoder::Encoder::process_encoding_queue
             at ./prusti-viper/src/encoder/encoder.rs:1466:17
   8: prusti_viper::verifier::Verifier::verify
             at ./prusti-viper/src/verifier.rs:243:9
   9: prusti_driver::verifier::verify
             at ./prusti/src/verifier.rs:48:39
  10: <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis::{{closure}}
             at ./prusti/src/callbacks.rs:82:17
  11: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /home/till/.rustup/toolchains/nightly-2020-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/compiler/rustc_interface/src/passes.rs:729:42
  12: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /home/till/.rustup/toolchains/nightly-2020-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/compiler/rustc_middle/src/ty/context.rs:1719:50
  13: rustc_middle::ty::context::tls::set_tlv
             at /home/till/.rustup/toolchains/nightly-2020-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/compiler/rustc_middle/src/ty/context.rs:1703:9
  14: rustc_middle::ty::context::tls::enter_context
             at /home/till/.rustup/toolchains/nightly-2020-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/compiler/rustc_middle/src/ty/context.rs:1719:9
  15: rustc_interface::passes::QueryContext::enter
             at /home/till/.rustup/toolchains/nightly-2020-11-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/compiler/rustc_interface/src/passes.rs:729:9
  16: <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis
             at ./prusti/src/callbacks.rs:48:9
  17: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  18: rustc_span::with_source_map
  19: rustc_interface::interface::create_compiler_and_run
  20: rustc_span::with_session_globals

  ```
  
</details>

**Comment by fpoli** [comment]
Now, the encoding of this program does not terminate.

**Comment by alexanderjsummers** [comment]
I guess the issue could be due to non-linear arithmetic (from the postcondition) making the underlying solver unstable
