### ISSUE TITLE
Prusti panic involving multiple dereferences in conditional

### ISSUE THREAD

**Issue by frececroka** [viperproject/prusti-dev#33]
This causes Prusti to panic:

```
fn find(b: &mut bool) -> &mut bool {
    if *b { b }
    else if *b { b }
    else { b }
}
```

The backtrace:
```
thread 'main' panicked at 'internal error: entered unreachable code: Invalid addition: write + write', prusti-viper/src/encoder/vir/ast/common.rs:101:18
stack backtrace:
...
 7: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:413
 8: prusti_viper::encoder::foldunfold::state::State::restore_dropped_perm
 9: prusti_viper::encoder::foldunfold::FoldUnfold::process_expire_borrows
10: <prusti_viper::encoder::foldunfold::FoldUnfold<'p, 'v, 'r, 'a, 'tcx> as prusti_viper::encoder::vir::cfg::visitor::CfgReplacer<prusti_viper::encoder::foldunfold::branch_ctxt::BranchCtxt<'p>, alloc::vec::Vec<prusti_viper::encoder::foldunfold::action::Action>>>::replace_stmt
11: <prusti_viper::encoder::foldunfold::FoldUnfold<'p, 'v, 'r, 'a, 'tcx> as prusti_viper::encoder::vir::cfg::visitor::CfgReplacer<prusti_viper::encoder::foldunfold::branch_ctxt::BranchCtxt<'p>, alloc::vec::Vec<prusti_viper::encoder::foldunfold::action::Action>>>::replace_stmt
12: prusti_viper::encoder::foldunfold::add_fold_unfold
13: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode
14: prusti_viper::encoder::encoder::Encoder::process_encoding_queue
15: prusti_viper::verifier::Verifier::verify
16: prusti::verifier::verify
...
```

**Comment by fpoli** [comment]
The example now seems to work fine.
