### ISSUE TITLE
Verification involving generics crashes Prusti

### ISSUE THREAD

**Issue by jmc-figueira** [viperproject/prusti-dev#353]
Similarly to #352, I encountered a panic when verifying the following code:

```Rust
use prusti_contracts::*;
use std::collections::HashSet;
use std::hash::Hash;

fn main() {

}

// Commented out as https://viperproject.github.io/prusti-dev/user-guide/verify/external.html
// mentions external_spec has issues when combined with generics
/*#[extern_spec]
impl<T> HashSet<T> {
    #[ensures(result.is_empty())]
    fn new() -> Self;

    #[pure]
    #[ensures(result >= 0)]
    fn len(&self) -> usize;

    #[pure]
    #[ensures(result ==> self.len() > 0)]
    #[ensures(!result ==> self.len() == 0)]
    fn is_empty(&self) -> bool;

    #[ensures(self.is_empty())]
    fn clear(&mut self);
}*/

struct WrappedHashSet<T>{
    set: HashSet<T>
}

impl<T: Hash + Eq> WrappedHashSet<T>{
    #[trusted]
    #[ensures(result.is_empty())]
    fn new() -> Self {
        WrappedHashSet{
            set: HashSet::new()
        }
    }

    #[pure]
    #[trusted]
    #[ensures(result >= 0)]
    fn len(&self) -> usize {
        return self.set.len();
    }

    #[pure]
    #[trusted]
    #[ensures(result ==> self.len() > 0)]
    #[ensures(!result ==> self.len() == 0)]
    fn is_empty(&self) -> bool {
        self.set.is_empty()
    }

    #[trusted]
    #[ensures(self.is_empty())]
    fn clear(&mut self) {
        self.set.clear();
    }

    #[trusted]
    #[pure]
    fn contains(&self, elem: &T) -> bool {
        self.set.contains(elem)
    }

    #[trusted]
    #[ensures(result ==> !old(self).contains(&elem))]
    #[ensures(!result ==> old(self).contains(&elem))]
    fn insert(&mut self, elem: T) -> bool {
        self.set.insert(elem)
    }
}

// Taken from Meirim, Filipe, Mário Pereira, and Carla Ferreira. 
// "CISE3: Verifying Weakly Consistent Applications with Why3." arXiv preprint arXiv:2010.06622 (2020).
struct RemoveWinsSet<T>{
    remove_wins_adds: WrappedHashSet<T>,
    remove_wins_removes: WrappedHashSet<T>
}

impl<T: Hash + Eq> RemoveWinsSet<T>{
    #[ensures(result.remove_wins_adds.is_empty() && result.remove_wins_removes.is_empty())]
    fn new() -> Self {
        RemoveWinsSet{
            remove_wins_adds: WrappedHashSet::new(),
            remove_wins_removes: WrappedHashSet::new()
        }
    }

    #[ensures(self.remove_wins_adds.is_empty() && self.remove_wins_removes.is_empty())]
    fn empty_set(&mut self) {
        self.remove_wins_adds.clear();
        self.remove_wins_removes.clear();
    }

    #[pure]
    #[ensures(result ==> self.remove_wins_adds.contains(&elem) && !self.remove_wins_removes.contains(&elem))]
    #[ensures(!result ==> !self.remove_wins_adds.contains(&elem) || self.remove_wins_removes.contains(&elem))]
    fn in_set(&self, elem: T) -> bool {
        self.remove_wins_adds.contains(&elem) && !self.remove_wins_removes.contains(&elem)
    }

    #[ensures(self.remove_wins_adds.contains(&elem))]
    fn add_elem(&mut self, elem: T){
        self.remove_wins_adds.insert(elem);
    }

    #[ensures(self.remove_wins_removes.contains(&elem))]
    fn remove_elem(&mut self, elem: T){
        self.remove_wins_removes.insert(elem);
    }
}
```

The error produced is the following:

```
Verification of 12 items...
thread 'rustc' panicked at 'not implemented: Param(T/#0)', prusti-viper/src/encoder/type_encoder.rs:181:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new

note: Prusti version: {commit 6e9dbad5 2021-01-06 15:15:04 UTC, built on 2021-01-08 15:01:51 UTC}

warning: 9 warnings emitted
```

If I instead use, for instance, `i64` for the `RemoveWinsSet` instead of making it generic, the error produced is different:

```
Verification of 12 items...
thread 'rustc' panicked at 'failed generation of folding/unfolding in DefId(0:55 ~ remove_wins_set[317d]::{impl#1}::in_set)', prusti-viper/src/encoder/pure_function_encoder.rs:257:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new

note: Prusti version: {commit 6e9dbad5 2021-01-06 15:15:04 UTC, built on 2021-01-08 15:01:51 UTC}

warning: 9 warnings emitted
```

I apologize if this and #352 are already-known limitations of Prusti, as I am still testing the waters and the documentation did not specify (or I was unable to figure out) whether the specifications I was trying are supported or not (although they seem not to be, judging from the compiler errors).

**Comment by fpoli** [comment]
Regarding the "not implemented: Param(T/#0)" crash, it's indeed a bug in the handling of generics. Currently, Prusti uses a fragile regexp-based approach that should be rewritten. The main issue to track that is #187.

Regarding the "failed generation of folding/unfolding" crash I'm not sure what's the cause. We would have to debug it.

> I apologize if this and #352 are already-known limitations of Prusti, as I am still testing the waters and the documentation did not specify (or I was unable to figure out) whether the specifications I was trying are supported or not (although they seem not to be, judging from the compiler errors).

No problem. Thanks for providing the full input program; it makes debugging easier. A Prusti crash is generally always worth an issue, because we have dedicated error messages for unsupported features.

**Comment by Aurel300** [comment]
These are no longer crashes, but there are still internal errors. `in_set` correctly reports that `elem` is not a copy type, so it needs to be changed to `&T`. The extern specs also work with generics now (see [`set.rs`](https://github.com/viperproject/prusti-dev/blob/b152e5a8786fce65dc34990ee50a9050b365f7f9/prusti-tests/tests/verify_overflow/pass/extern-spec/set.rs#L24-L57)).

However, we still get internal errors for the calls to `self.remove_wins_*.insert(elem)`

**Comment by Aurel300** [comment]
With fixed specifications, both the wrapper and an `extern_spec` version works.
