### ISSUE TITLE
rustc panic Option::unwrap() at prusti-viper/src/utils/type_visitor.rs:272:50

### ISSUE THREAD

**Issue by zgrannan** [viperproject/prusti-dev#358]
While running `prusti-rustc` on the following code:

```rust
struct Params {
    letter: char,
    password: String
}

fn check(params: Params) -> usize {
    return params.password.chars().filter(|c| c == &params.letter).count();
}

fn main() {
    check(Params{letter: 'a', password: "123".to_string()});
}
```
the following output is observed:
```
> env RUST_BACKTRACE=full prusti-rustc src/mini.rs
  __          __        __  ___             
 |__)  _\/_  |__) |  | /__`  |   ____\/_  | 
 |      /\   |  \ \__/ .__/  |       /\   | 

{commit 22a4eb83 2021-01-18 13:24:14 UTC, built on 2021-01-19 16:06:37 UTC}


Verification of 3 items...
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', prusti-viper/src/utils/type_visitor.rs:272:50
stack backtrace:
   0:     0x7f8a22c0bd67 - std::backtrace_rs::backtrace::libunwind::trace::h8bc78f7bc1f75bdb
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f8a22c0bd67 - std::backtrace_rs::backtrace::trace_unsynchronized::ha4c961c9576f95ba
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f8a22c0bd67 - std::sys_common::backtrace::_print_fmt::hc20cfdc233d6eb02
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f8a22c0bd67 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04bea14549780a0f
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f8a22c7c8ec - core::fmt::write::h3868db8542c90941
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/core/src/fmt/mod.rs:1096:17
   5:     0x7f8a22bfdbe2 - std::io::Write::write_fmt::h55dd75636eef6a5c
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/std/src/io/mod.rs:1564:15
   6:     0x7f8a22c0fa05 - std::sys_common::backtrace::_print::h6439e8525077c7da
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f8a22c0fa05 - std::sys_common::backtrace::print::h02b685f728ce3931
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f8a22c0fa05 - std::panicking::default_hook::{{closure}}::h7c29625065fafae1
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/std/src/panicking.rs:208:50
   9:     0x7f8a22c0f563 - std::panicking::default_hook::hba441710bb71f4d5
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/std/src/panicking.rs:225:9
  10:     0x560ed3d0a622 - prusti_driver::report_prusti_ice::hf9cb856b19c082f5
  11:     0x7f8a22c10306 - std::panicking::rust_panic_with_hook::ha936eb00e51bc4d9
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/std/src/panicking.rs:595:17
  12:     0x7f8a22c0fdf7 - std::panicking::begin_panic_handler::{{closure}}::hcd15140e0238536e
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/std/src/panicking.rs:495:13
  13:     0x7f8a22c0c22c - std::sys_common::backtrace::__rust_end_short_backtrace::hb13a021bb64823a1
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7f8a22c0fd89 - rust_begin_unwind
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/std/src/panicking.rs:493:5
  15:     0x7f8a22c78d31 - core::panicking::panic_fmt::h20225113c4a2f8fd
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/core/src/panicking.rs:92:14
  16:     0x7f8a22c78c7d - core::panicking::panic::h35b77276aa4b0c12
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/core/src/panicking.rs:50:5
  17:     0x560ed3e82ea1 - prusti_viper::utils::type_visitor::walk_closure::h72523c0fd6aa2706
  18:     0x560ed3d4c70d - prusti_viper::utils::type_visitor::TypeVisitor::visit_ty::hde5f4890a527bbe5
  19:     0x560ed3d48a9f - prusti_viper::encoder::borrows::compute_procedure_contract::had5f1e12fe42da31
  20:     0x560ed3e56866 - prusti_viper::encoder::encoder::Encoder::get_procedure_contract_for_call::h30999cdca0bdc977
  21:     0x560ed3ded1f4 - prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_impure_function_call::h6b85279f0fc44c8f
  22:     0x560ed3de4ff4 - prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_terminator::h0ff10c0500820350
  23:     0x560ed3dcf1f2 - prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_statement_at::hd8bc3a6d942422ef
  24:     0x560ed3dc8025 - prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_blocks_group::h417cb036e0e9e75d
  25:     0x560ed3dc0047 - prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode::h5a80c9e339833fba
  26:     0x560ed3e5b3ba - prusti_viper::encoder::encoder::Encoder::encode_procedure::ha415692902e911c0
  27:     0x560ed3e67adf - prusti_viper::encoder::encoder::Encoder::process_encoding_queue::hf16fb620a5826dd9
  28:     0x560ed3d2f35c - prusti_viper::verifier::Verifier::verify::h203c5edb52ddd337
  29:     0x560ed3cf88d3 - prusti_driver::verifier::verify::h278d5f7c9df0c39b
  30:     0x560ed3cfa6a7 - rustc_interface::passes::QueryContext::enter::hceae649f3a014e03
  31:     0x560ed3cfcc52 - <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis::hbff8d3dff3012dc7
  32:     0x7f8a258452e9 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h218ca720d3205e5f
  33:     0x7f8a2583ae54 - rustc_span::with_source_map::h4befef2d05638fd3
  34:     0x7f8a2584653a - rustc_interface::interface::create_compiler_and_run::h590e12a25d2eb81f
  35:     0x7f8a2583b6a7 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf43b1d3900929834
  36:     0x7f8a258200ea - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd515068460c27675
  37:     0x7f8a22c205aa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8ffdf8dc1f37e360
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/alloc/src/boxed.rs:1484:9
  38:     0x7f8a22c205aa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h74f6ec149ce6acc8
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/alloc/src/boxed.rs:1484:9
  39:     0x7f8a22c205aa - std::sys::unix::thread::Thread::new::thread_start::h565bef3956c58d58
                               at /rustc/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/library/std/src/sys/unix/thread.rs:71:17
  40:     0x7f8a215e9e9e - start_thread
  41:     0x7f8a213d358f - __GI___clone
  42:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new

note: Prusti version: {commit 22a4eb83 2021-01-18 13:24:14 UTC, built on 2021-01-19 16:06:37 UTC}

query stack during panic:
end of query stack
```

**Comment by zgrannan** [comment]
Instead,  if the `check()` method is marked as `#[trusted]`, the following output is observed:

```
error: [Prusti internal error] generating fold-unfold Viper statements failed (FailedToObtain(Acc(Field(Field(Field(Field(Local(_1: Ref(ref$closure$0_11$3$16578871950627681774), Position { line: 11, column: 52, id: 40 }), val_ref: Ref(closure$0_11$3$16578871950627681774), Position { line: 11, column: 52, id: 40 }), closure_0: Ref(ref$m_Params$_beg_$_end_), Position { line: 11, column: 52, id: 40 }), val_ref: Ref(m_Params$_beg_$_end_), Position { line: 11, column: 52, id: 40 }), f$letter: Ref(char), Position { line: 11, column: 52, id: 40 }), read)))
  --> src/mini.rs:11:43
   |
11 |     return params.password.chars().filter(|c| c == &params.letter).count();
```

**Comment by fpoli** [comment]
From a quick look the issue is with the closure `|c| c == &params.letter` – closures are not well supported. Prusti should at least report an "unsupported feature" error message instead of crashing.

**Comment by Aurel300** [comment]
Let's not actually touch this until after CAV.

**Comment by fpoli** [comment]
The error message is now

```
error: [Prusti: unsupported feature] higher-ranked lifetimes and types are not supported
 --> program.rs:7:12
  |
7 |     return params.password.chars().filter(|c| c == &params.letter).count();
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I think we can close the issue as soon as we add a regression test for this. Do you agree or is the error message still not good enough?

**Comment by Aurel300** [comment]
It's not great because higher-ranked lifetimes are implicitly introduced (by way of the `Fn*` type), but at least it's a proper error and at the correct position.
