### ISSUE TITLE
Usage of function defined in external crate as part of lambda breaks Prusti

### ISSUE THREAD

**Issue by zgrannan** [viperproject/prusti-dev#406]
When I attempt to verify the following code:

```rust
use serde::Deserializer;

extern crate prusti_contracts;
use prusti_contracts::*;

#[trusted]
pub fn deserialize<'de, D>(deserializer: D, bytes: Vec<Vec<u8>>) -> Result<Vec<String>, D::Error>
where
    D: Deserializer<'de>,
{
    return bytes
        .into_iter()
        .map(|s| String::from_utf8(s).map_err(serde::de::Error::custom))
        .collect()
}

fn main() {}
```

with the following `Cargo.toml`:

```
[package]
name = "repro"
version = "0.0.1"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
```

I encounter the following error:

```
~/prusti-reproduce env RUST_BACKTRACE=1 cargo-prusti --verbose
       Fresh unicode-xid v0.2.1
       Fresh proc-macro2 v1.0.24
       Fresh quote v1.0.9
       Fresh syn v1.0.60
       Fresh serde_derive v1.0.123
       Fresh serde v1.0.123
    Checking repro v0.0.1 (/home/zgrannan/prusti-reproduce)
     Running `/home/zgrannan/prusti-dev/target/release/prusti-rustc rustc --crate-name repro --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C metadata=5712adcc0cd84e54 -C extra-filename=-5712adcc0cd84e54 --out-dir /home/zgrannan/prusti-reproduce/target/debug/deps -C incremental=/home/zgrannan/prusti-reproduce/target/debug/incremental -L dependency=/home/zgrannan/prusti-reproduce/target/debug/deps --extern serde=/home/zgrannan/prusti-reproduce/target/debug/deps/libserde-51be562b67e2a38c.rmeta`
warning: unused variable: `deserializer`
 --> src/main.rs:7:28
  |
7 | pub fn deserialize<'de, D>(deserializer: D, bytes: Vec<Vec<u8>>) -> Result<Vec<String>, D::Error>
  |                            ^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_deserializer`
  |
  = note: `#[warn(unused_variables)]` on by default

thread 'rustc' panicked at 'DefId::expect_local: `DefId(21:8130 ~ serde[9e58]::de::Error::custom)` isn't local', /nix/store/w6arrraaagja91g663ymbsaisb2hyn7w-rust-1.52.0-nightly-2021-02-11-e9920ef77/lib/rustlib/src/rust/compiler/rustc_span/src/def_id.rs:175:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e9920ef7749d11fc71cc32ca4ba055bcfeaab945/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e9920ef7749d11fc71cc32ca4ba055bcfeaab945/library/std/src/panicking.rs:435:5
   2: rustc_span::def_id::DefId::expect_local::{{closure}}
   3: prusti_interface::environment::procedure::Procedure::new
   4: prusti_interface::environment::Environment::get_procedure
   5: prusti_viper::encoder::encoder::Encoder::encode_spec_funcs
   6: prusti_viper::encoder::encoder::Encoder::encode_const_expr
   7: prusti_viper::encoder::mir_encoder::MirEncoder::encode_operand_expr
   8: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_impure_function_call
   9: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_terminator
  10: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_statement_at
  11: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_blocks_group
  12: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode
  13: prusti_viper::encoder::encoder::Encoder::encode_procedure
  14: prusti_viper::encoder::encoder::Encoder::process_encoding_queue
  15: prusti_viper::verifier::Verifier::verify
  16: prusti_driver::verifier::verify
  17: <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis
  18: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  19: rustc_span::with_source_map
  20: rustc_interface::interface::create_compiler_and_run
  21: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new

note: Prusti version: {commit 2ff2bf2e 2021-02-10 08:38:15 UTC, built on 2021-02-12 20:01:35 UTC}

query stack during panic:
end of query stack
warning: 1 warning emitted

error: could not compile `repro`

Caused by:
  process didn't exit successfully: `/home/zgrannan/prusti-dev/target/release/prusti-rustc rustc --crate-name repro --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 -C metadata=5712adcc0cd84e54 -C extra-filename=-5712adcc0cd84e54 --out-dir /home/zgrannan/prusti-reproduce/target/debug/deps -C incremental=/home/zgrannan/prusti-reproduce/target/debug/incremental -L dependency=/home/zgrannan/prusti-reproduce/target/debug/deps --extern serde=/home/zgrannan/prusti-reproduce/target/debug/deps/libserde-51be562b67e2a38c.rmeta` (exit code: 101)
```

I think this is caused by being a combination of using the `serde::de::Error::custom` function from an external crate, and also using it within a lambda. 

I don't care to verify the function annotated with `#[trusted]`, but at it would be nice for Prusti to ignore it.

**Comment by Aurel300** [comment]
You are right, the `serde::de::Error::custom` function is called from within a closure, and a closure is desugared into a separate function by the Rust compiler, so the `#[trusted]` annotation doesn't apply transitively. This is something we might want to fix, although we should be careful not to do if IF there is a specification attached to the closure (pending more closure verification work…).

For now, I wonder if something like this would work?

```rust
#[extern_spec]
impl serde::de::Error {
    #[trusted] fn custom<T>(msg: T);
}
```

It is also a trait, and the function has a type parameter, so not a lot of hope… Another alternative would be to extract the closure into a function and annotate it with `#[trusted]` as well, although this is only possible here because there is no captured state:

```rust
#[trusted]
fn map_error(s: Vec<u8>) -> Result<String, serde::de::Error> { // unsure about the exact types
    String::from_utf8(s).map_err(serde::de::Error::custom)
}
```
