### ISSUE TITLE
internal error: entered unreachable code at prusti-viper/src/encoder/procedure_encoder.rs:2057:37

### ISSUE THREAD

**Issue by zgrannan** [viperproject/prusti-dev#410]
For the following code: 

```rust
pub fn max_by_key<A, B: Ord>(a: A, b: A, key: impl Fn(&A) -> B) -> A {
    if key(&a) > key(&b) {
        a
    } else {
        b
    }
}

fn main() {}
```
The output is:

```
~/prusti-reproduce env RUST_BACKTRACE=1 prusti-rustc main.rs
  __          __        __  ___             
 |__)  _\/_  |__) |  | /__`  |   ____\/_  | 
 |      /\   |  \ \__/ .__/  |       /\   | 

{commit b51ec334 2021-02-15 19:43:59 UTC, built on 2021-02-16 06:44:48 UTC}


Verification of 2 items...
thread 'rustc' panicked at 'internal error: entered unreachable code', prusti-viper/src/encoder/procedure_encoder.rs:2057:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5fa22fe6f821ac3801d05f624b123dda25fde32c/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/5fa22fe6f821ac3801d05f624b123dda25fde32c/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/5fa22fe6f821ac3801d05f624b123dda25fde32c/library/core/src/panicking.rs:50:5
   3: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_terminator
   4: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_statement_at
   5: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_blocks_group
   6: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode
   7: prusti_viper::encoder::encoder::Encoder::encode_procedure
   8: prusti_viper::encoder::encoder::Encoder::process_encoding_queue
   9: prusti_viper::verifier::Verifier::verify
  10: prusti_driver::verifier::verify
  11: rustc_interface::passes::QueryContext::enter
  12: <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis
  13: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  14: rustc_span::with_source_map
  15: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new

note: Prusti version: {commit b51ec334 2021-02-15 19:43:59 UTC, built on 2021-02-16 06:44:48 UTC}
```

Adding `#[trusted]` to `max_by_key` it go away, but finding the cause in a large codebase can be challenging because prusti doesn't indicate the origin of the error.

Upadting `procedure_encoder.rs` at  line 2057 to:
```rust
unimplemented!("Unsupported kind {:?} at {:?}", cl_type.kind(), term.source_info.span)
```

Provides a more useful error message, but I didn't create a PR since there may be a better resolution for this issue.

**Comment by fpoli** [comment]
The panic is at `./prusti-viper/src/encoder/procedure_encoder.rs:2056`:
https://github.com/viperproject/prusti-dev/blob/2a34987fe9c65c79c6a50120d502dd8a3589b790/prusti-viper/src/encoder/procedure_encoder.rs#L2041-L2058

We should report an error message saying that we don't support calls of `std::ops::Fn::call` that are not closures. (Although, also support for closures is not yet complete @Aurel300?)

**Comment by Aurel300** [comment]
Yes, that version of `Fn::call` is incomplete. This is actually the same as a higher-order call to a type parameter (except it is an `impl`), the encoding of which we know how to do, but have not yet implemented. This should be resolved by the time the next closure PR™ lands.
