### ISSUE TITLE
Prusti panics on an internal unwrap and deriving Debug

### ISSUE THREAD

**Issue by Kixiron** [viperproject/prusti-dev#416]
Tried to write some Prusti but it panics on an internal unwrap.

```
❯ prusti-rustc -V
  __          __        __  ___
 |__)  _\/_  |__) |  | /__`  |   ____\/_  |
 |      /\   |  \ \__/ .__/  |       /\   |

{commit 074a8ca 2021-02-17 16:48:58 UTC, built on 2021-02-17 16:58:37 UTC}


rustc 1.52.0-nightly (5fa22fe6f 2021-02-14)
```

<details>
<summary>Code</summary>

```rust
// main.rs
use prusti_contracts::*;

fn main() {}

#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(transparent)]
pub struct SafeVec<T>(Vec<T>);

impl<T> SafeVec<T> {
    #[pure]
    #[trusted]
    pub fn len(&self) -> usize {
        self.0.len()
    }

    #[pure]
    #[trusted]
    #[ensures(result ==> self.len() == 0)]
    #[ensures(!result ==> self.len() > 0)]
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    #[requires(!self.is_empty())]
    #[ensures(self.len() == old(self.len()) - 1)]
    pub fn pop_safe(&mut self) -> T {
        todo!()
    }

    #[pure]
    #[requires(idx < self.len())]
    #[ensures(self.len() == old(self.len()) - 1)]
    pub fn get_safe(&self, idx: usize) -> &T {
        // Safety: `idx` will always be in-bounds
        unsafe { self.get_unchecked(idx) }
    }

    #[requires(idx < self.len())]
    #[ensures(self.len() == old(self).len() - 1)]
    pub fn get_mut_safe(&mut self, idx: usize) -> &mut T {
        // Safety: `idx` will always be in-bounds
        unsafe { self.get_unchecked_mut(idx) }
    }

    #[pure]
    pub unsafe fn get_unchecked(&self, idx: usize) -> &T {
        self.0.get_unchecked(idx)
    }

    pub unsafe fn get_unchecked_mut(&mut self, idx: usize) -> &mut T {
        self.0.get_unchecked_mut(idx)
    }
}
```

```toml
# Cargo.toml
[package]
name = "prusti-test"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies.prusti-contracts]
git = "https://github.com/viperproject/prusti-dev"
rev = "074a8ca2ec5233cd713fadf28b078bf69d1f9f9d"
```

```toml
# Prusti.toml
CHECK_OVERFLOWS = true
```

</details>

<details>
<summary>Backtrace</summary>

```
❯ prusti-rustc --edition=2018 src/main.rs
  __          __        __  ___
 |__)  _\/_  |__) |  | /__`  |   ____\/_  |
 |      /\   |  \ \__/ .__/  |       /\   |

{commit 074a8ca 2021-02-17 16:48:58 UTC, built on 2021-02-17 16:58:37 UTC}


Verification of 15 items...
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', prusti-viper\src\encoder\foldunfold\mod.rs:1260:45
stack backtrace:
   0:     0x7ff92b81857e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h160322fcc0f12a19
   1:     0x7ff92b84461b - core::fmt::write::ha3ea633b18d2da75
   2:     0x7ff92b80b6c8 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h0112a934cd010a1c
   3:     0x7ff92b81c74d - std::panicking::take_hook::h7c389d310fc84231
   4:     0x7ff92b81c219 - std::panicking::take_hook::h7c389d310fc84231
   5:     0x7ff6888bcb94 - <unknown>
   6:     0x7ff92b81d1b2 - std::panicking::rust_panic_with_hook::h13af0da83034d6f3
   7:     0x7ff92b81cc73 - rust_begin_unwind
   8:     0x7ff92b818f0f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h160322fcc0f12a19
   9:     0x7ff92b81cbf9 - rust_begin_unwind
  10:     0x7ff92b8408d0 - core::panicking::panic_fmt::h45da916c710b88f7
  11:     0x7ff92b84081c - core::panicking::panic::h3a7a516f2be28c18
  12:     0x7ff688a2c30e - <unknown>
  13:     0x7ff6889e55f8 - <unknown>
  14:     0x7ff688a2c6da - <unknown>
  15:     0x7ff688a06b43 - <unknown>
  16:     0x7ff688a06c8a - <unknown>
  17:     0x7ff6889e5a7f - <unknown>
  18:     0x7ff688a2c6da - <unknown>
  19:     0x7ff688a06b43 - <unknown>
  20:     0x7ff688a06c8a - <unknown>
  21:     0x7ff6889e5a7f - <unknown>
  22:     0x7ff688a2c6da - <unknown>
  23:     0x7ff688a06b43 - <unknown>
  24:     0x7ff688a06c8a - <unknown>
  25:     0x7ff6889e5a7f - <unknown>
  26:     0x7ff688a2c6da - <unknown>
  27:     0x7ff688a06b43 - <unknown>
  28:     0x7ff6889e561c - <unknown>
  29:     0x7ff688a2c6da - <unknown>
  30:     0x7ff688a06b43 - <unknown>
  31:     0x7ff688a06537 - <unknown>
  32:     0x7ff6889e56f7 - <unknown>
  33:     0x7ff688a2c6da - <unknown>
  34:     0x7ff688a06b43 - <unknown>
  35:     0x7ff688a06c8a - <unknown>
  36:     0x7ff6889e5a7f - <unknown>
  37:     0x7ff688a2c6da - <unknown>
  38:     0x7ff688a13369 - <unknown>
  39:     0x7ff6888d468f - <unknown>
  40:     0x7ff68891ab3f - <unknown>
  41:     0x7ff688aa2edb - <unknown>
  42:     0x7ff688a13ba4 - <unknown>
  43:     0x7ff688aff3d9 - <unknown>
  44:     0x7ff688afb222 - <unknown>
  45:     0x7ff688b3ae51 - <unknown>
  46:     0x7ff688b4084b - <unknown>
  47:     0x7ff6888f1dc4 - <unknown>
  48:     0x7ff6888a9e5e - <unknown>
  49:     0x7ff6888ac039 - <unknown>
  50:     0x7ff6888ae66d - <unknown>
  51:     0x7ff91d422ab3 - rustc_ast::util::parser::prec_let_scrutinee_needs_par::hfc7ab7b91c80b01e
  52:     0x7ff91d3fc17c - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h565c544a3fcd0386
  53:     0x7ff91d419009 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h565c544a3fcd0386
  54:     0x7ff91d425cee - rustc_ast::util::parser::prec_let_scrutinee_needs_par::hfc7ab7b91c80b01e
  55:     0x7ff91d39962d - <tracing_subscriber::util::TryInitError as core::fmt::Display>::fmt::ha43055df5546b109
  56:     0x7ff92b82c9fa - std::sys::windows::thread::Thread::new::hd38a560d738a063d
  57:     0x7ff99f077034 - BaseThreadInitThunk
  58:     0x7ff99f97d241 - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new

note: Prusti version: {commit 074a8ca 2021-02-17 16:48:58 UTC, built on 2021-02-17 16:58:37 UTC}

query stack during panic:
end of query stack
```

</details>

Interestingly, I actually managed to find multiple bugs here which is fun, this one happens when I add `Debug` to the list of derives on `SafeVec`:

<details>
<summary>Code</summary>

```rust
// main.rs
use prusti_contracts::*;

fn main() {}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)] // Only change is adding Debug here
#[repr(transparent)]
pub struct SafeVec<T>(Vec<T>);

impl<T> SafeVec<T> {
    #[pure]
    #[trusted]
    pub fn len(&self) -> usize {
        self.0.len()
    }

    #[pure]
    #[trusted]
    #[ensures(result ==> self.len() == 0)]
    #[ensures(!result ==> self.len() > 0)]
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    #[requires(!self.is_empty())]
    #[ensures(self.len() == old(self.len()) - 1)]
    pub fn pop_safe(&mut self) -> T {
        todo!()
    }

    #[pure]
    #[requires(idx < self.len())]
    #[ensures(self.len() == old(self.len()) - 1)]
    pub fn get_safe(&self, idx: usize) -> &T {
        // Safety: `idx` will always be in-bounds
        unsafe { self.get_unchecked(idx) }
    }

    #[requires(idx < self.len())]
    #[ensures(self.len() == old(self).len() - 1)]
    pub fn get_mut_safe(&mut self, idx: usize) -> &mut T {
        // Safety: `idx` will always be in-bounds
        unsafe { self.get_unchecked_mut(idx) }
    }

    #[pure]
    pub unsafe fn get_unchecked(&self, idx: usize) -> &T {
        self.0.get_unchecked(idx)
    }

    pub unsafe fn get_unchecked_mut(&mut self, idx: usize) -> &mut T {
        self.0.get_unchecked_mut(idx)
    }
}
```

```toml
# Cargo.toml
[package]
name = "prusti-test"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies.prusti-contracts]
git = "https://github.com/viperproject/prusti-dev"
rev = "074a8ca2ec5233cd713fadf28b078bf69d1f9f9d"
```

```toml
# Prusti.toml
CHECK_OVERFLOWS = true
```

</details>

<details>
<summary>Backtrace</summary>

```
❯ prusti-rustc --edition=2018 src/main.rs
  __          __        __  ___
 |__)  _\/_  |__) |  | /__`  |   ____\/_  |
 |      /\   |  \ \__/ .__/  |       /\   |

{commit 074a8ca 2021-02-17 16:48:58 UTC, built on 2021-02-17 16:58:37 UTC}


Verification of 16 items...
error: [Prusti: unsupported feature] cast statements that create loans are not supported
 --> src/main.rs:7:23
  |
7 | pub struct SafeVec<T>(Vec<T>);
  |                       ^^^^^^
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', prusti-viper\src\encoder\foldunfold\mod.rs:1260:45
stack backtrace:
   0:     0x7ff92b81857e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h160322fcc0f12a19
   1:     0x7ff92b84461b - core::fmt::write::ha3ea633b18d2da75
   2:     0x7ff92b80b6c8 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h0112a934cd010a1c
   3:     0x7ff92b81c74d - std::panicking::take_hook::h7c389d310fc84231
   4:     0x7ff92b81c219 - std::panicking::take_hook::h7c389d310fc84231
   5:     0x7ff6888bcb94 - <unknown>
   6:     0x7ff92b81d1b2 - std::panicking::rust_panic_with_hook::h13af0da83034d6f3
   7:     0x7ff92b81cc73 - rust_begin_unwind
   8:     0x7ff92b818f0f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h160322fcc0f12a19
   9:     0x7ff92b81cbf9 - rust_begin_unwind
  10:     0x7ff92b8408d0 - core::panicking::panic_fmt::h45da916c710b88f7
  11:     0x7ff92b84081c - core::panicking::panic::h3a7a516f2be28c18
  12:     0x7ff688a2c30e - <unknown>
  13:     0x7ff6889e55f8 - <unknown>
  14:     0x7ff688a2c6da - <unknown>
  15:     0x7ff688a06b43 - <unknown>
  16:     0x7ff688a06c8a - <unknown>
  17:     0x7ff6889e5a7f - <unknown>
  18:     0x7ff688a2c6da - <unknown>
  19:     0x7ff688a06b43 - <unknown>
  20:     0x7ff688a06c8a - <unknown>
  21:     0x7ff6889e5a7f - <unknown>
  22:     0x7ff688a2c6da - <unknown>
  23:     0x7ff688a06b43 - <unknown>
  24:     0x7ff688a06c8a - <unknown>
  25:     0x7ff6889e5a7f - <unknown>
  26:     0x7ff688a2c6da - <unknown>
  27:     0x7ff688a06b43 - <unknown>
  28:     0x7ff6889e561c - <unknown>
  29:     0x7ff688a2c6da - <unknown>
  30:     0x7ff688a06b43 - <unknown>
  31:     0x7ff688a06537 - <unknown>
  32:     0x7ff6889e56f7 - <unknown>
  33:     0x7ff688a2c6da - <unknown>
  34:     0x7ff688a06b43 - <unknown>
  35:     0x7ff688a06c8a - <unknown>
  36:     0x7ff6889e5a7f - <unknown>
  37:     0x7ff688a2c6da - <unknown>
  38:     0x7ff688a13369 - <unknown>
  39:     0x7ff6888d468f - <unknown>
  40:     0x7ff68891ab3f - <unknown>
  41:     0x7ff688aa2edb - <unknown>
  42:     0x7ff688a13ba4 - <unknown>
  43:     0x7ff688aff3d9 - <unknown>
  44:     0x7ff688afb222 - <unknown>
  45:     0x7ff688b3ae51 - <unknown>
  46:     0x7ff688b4084b - <unknown>
  47:     0x7ff6888f1dc4 - <unknown>
  48:     0x7ff6888a9e5e - <unknown>
  49:     0x7ff6888ac039 - <unknown>
  50:     0x7ff6888ae66d - <unknown>
  51:     0x7ff91d422ab3 - rustc_ast::util::parser::prec_let_scrutinee_needs_par::hfc7ab7b91c80b01e
  52:     0x7ff91d3fc17c - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h565c544a3fcd0386
  53:     0x7ff91d419009 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h565c544a3fcd0386
  54:     0x7ff91d425cee - rustc_ast::util::parser::prec_let_scrutinee_needs_par::hfc7ab7b91c80b01e
  55:     0x7ff91d39962d - <tracing_subscriber::util::TryInitError as core::fmt::Display>::fmt::ha43055df5546b109
  56:     0x7ff92b82c9fa - std::sys::windows::thread::Thread::new::hd38a560d738a063d
  57:     0x7ff99f077034 - BaseThreadInitThunk
  58:     0x7ff99f97d241 - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new

note: Prusti version: {commit 074a8ca 2021-02-17 16:48:58 UTC, built on 2021-02-17 16:58:37 UTC}

query stack during panic:
end of query stack
error: aborting due to previous error
```

</details>

**Comment by fpoli** [comment]
Thank you for the bug report! The main issue is that at the moment pure functions can only return booleans, integers and chars — we are still working on it. A workaround is to add a `lookup` function that returns a copy of the element instead of a shared reference, like here:

https://github.com/viperproject/prusti-dev/blob/074a8ca2ec5233cd713fadf28b078bf69d1f9f9d/prusti-tests/tests/verify/pass/rosetta/Heapsort.rs#L36-L41

**Comment by fpoli** [comment]
Regarding `get_mut_safe`, there are two issues:
* `old(..)` expressions can only be of type bool, integer or char. You can write `old(self.len())`.
* The postcondition tries to use `self`, which is blocked by the returned reference. @vakaras could you suggest how to write the pledge for that postcondition?

**Comment by vakaras** [comment]
>  @vakaras could you suggest how to write the pledge for that postcondition?

In theory, it would be this:

```rust
    #[requires(idx < self.len())]
    #[ensures(self.len() == old(self.len()) - 1)]
    #[after_expiry(self.len() == old(self.len()) - 1)]
    pub fn get_mut_safe(&mut self, idx: usize) -> &mut T {
        // Safety: `idx` will always be in-bounds
        unsafe { self.get_unchecked_mut(idx) }
    }
```
However, I am confused about why there is `-1` – retrieving an element should not change the length of the vector.

**Comment by Aurel300** [comment]
Maybe the `- 1` is an artifact from copy/pasting from the `pop` specification?
