### ISSUE TITLE
Compiler Panic with Option

### ISSUE THREAD

**Issue by jmc-figueira** [viperproject/prusti-dev#479]
While providing an `extern_spec` for a HashMap, a specification for the `insert` method, with a return type of `Option<u64>`, crashes the compiler:

```Rust
#[ensures(result == None ==> self.len() == old(self.len()) + 1)]
pub fn insert(&mut self, key: u64, value: u64) -> Option<u64>;
```

```
thread 'rustc' panicked at 'not implemented: Ref(ReErased, std::option::Option<u64>, Not)', prusti-viper/src/encoder/encoder.rs:1093:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d0695c9081b16077d0aed368bccaf437d77ff497/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/d0695c9081b16077d0aed368bccaf437d77ff497/library/core/src/panicking.rs:92:14
   2: prusti_viper::encoder::encoder::Encoder::encode_const_expr
   3: prusti_viper::encoder::mir_encoder::MirEncoder::encode_operand_expr
   4: <prusti_viper::encoder::pure_function_encoder::PureFunctionBackwardInterpreter as prusti_viper::encoder::mir_interpreter::BackwardMirInterpreter>::apply_statement
   5: prusti_viper::encoder::mir_interpreter::run_backward_interpretation
   6: prusti_viper::encoder::pure_function_encoder::PureFunctionEncoder::encode_body
   7: prusti_viper::encoder::encoder::Encoder::encode_pure_expression
   8: prusti_viper::encoder::spec_encoder::SpecEncoder::encode_expression
   9: prusti_viper::encoder::spec_encoder::SpecEncoder::encode_assertion
  10: prusti_viper::encoder::spec_encoder::SpecEncoder::encode_assertion
  11: prusti_viper::encoder::spec_encoder::encode_spec_assertion
  12: prusti_viper::encoder::encoder::Encoder::encode_assertion
  13: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_postcondition_expr
  14: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_impure_function_call
  15: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_terminator
  16: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_statement_at
  17: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_blocks_group
  18: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode
  19: prusti_viper::encoder::encoder::Encoder::encode_procedure
  20: prusti_viper::encoder::encoder::Encoder::process_encoding_queue
  21: prusti_viper::verifier::Verifier::verify
  22: prusti_driver::verifier::verify
  23: <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis
  24: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  25: rustc_span::with_source_map
  26: rustc_interface::interface::create_compiler_and_run
  27: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.
```

This might already be a well-known limitation/unimplemented feature, but as I found no other issues referencing this particular crash and it is a compiler crash, I decided I should report it.

**Comment by fpoli** [comment]
Thank you for the report! A full example to reproduce the issue:
```rust
use prusti_contracts::*;
use std::collections::HashMap;

#[extern_spec]
impl HashMap<u64, u64> {
    #[pure]
    pub fn len(&self) -> usize;

    #[ensures(result == None ==> self.len() == old(self.len()) + 1)]
    pub fn insert(&mut self, key: u64, value: u64) -> Option<u64>;
}

fn test(mut x: HashMap<u64, u64>) {
    let orig_len = x.len();
    if let None = x.insert(234, 345) {
        assert!(x.len() == orig_len + 1);
    }
}

fn main() {}
```

<details><summary>Stacktrace with line numbers</summary>

```
thread 'rustc' panicked at 'not implemented: Ref(ReErased, std::option::Option<u64>, Not)', prusti-viper/src/encoder/encoder.rs:1093:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d0695c9081b16077d0aed368bccaf437d77ff497/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/d0695c9081b16077d0aed368bccaf437d77ff497/library/core/src/panicking.rs:92:14
   2: prusti_viper::encoder::encoder::Encoder::encode_const_expr
             at ./prusti-viper/src/encoder/encoder.rs:1093:22
   3: prusti_viper::encoder::mir_encoder::MirEncoder::encode_operand_expr
             at ./prusti-viper/src/encoder/mir_encoder/mod.rs:377:19
   4: <prusti_viper::encoder::pure_function_encoder::PureFunctionBackwardInterpreter as prusti_viper::encoder::mir_interpreter::BackwardMirInterpreter>::apply_statement
             at ./prusti-viper/src/encoder/pure_function_encoder.rs:1062:52
   5: prusti_viper::encoder::mir_interpreter::run_backward_interpretation
             at ./prusti-viper/src/encoder/mir_interpreter.rs:74:13
   6: prusti_viper::encoder::pure_function_encoder::PureFunctionEncoder::encode_body
             at ./prusti-viper/src/encoder/pure_function_encoder.rs:70:21
   7: prusti_viper::encoder::encoder::Encoder::encode_pure_expression
             at ./prusti-viper/src/encoder/encoder.rs:1178:24
   8: prusti_viper::encoder::spec_encoder::SpecEncoder::encode_expression
             at ./prusti-viper/src/encoder/spec_encoder.rs:576:29
   9: prusti_viper::encoder::spec_encoder::SpecEncoder::encode_assertion
             at ./prusti-viper/src/encoder/spec_encoder.rs:198:17
  10: prusti_viper::encoder::spec_encoder::SpecEncoder::encode_assertion
             at ./prusti-viper/src/encoder/spec_encoder.rs:207:21
  11: prusti_viper::encoder::spec_encoder::encode_spec_assertion
             at ./prusti-viper/src/encoder/spec_encoder.rs:70:33
  12: prusti_viper::encoder::encoder::Encoder::encode_assertion
             at ./prusti-viper/src/encoder/encoder.rs:875:33
  13: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_postcondition_expr
             at ./prusti-viper/src/encoder/procedure_encoder.rs:3455:33
  14: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_impure_function_call
             at ./prusti-viper/src/encoder/procedure_encoder.rs:2631:13
  15: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_terminator
             at ./prusti-viper/src/encoder/procedure_encoder.rs:2140:37
  16: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_statement_at
             at ./prusti-viper/src/encoder/procedure_encoder.rs:1076:13
  17: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_block_terminator
             at ./prusti-viper/src/encoder/procedure_encoder.rs:1038:42
  18: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_block
             at ./prusti-viper/src/encoder/procedure_encoder.rs:935:43
  19: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_blocks_group
             at ./prusti-viper/src/encoder/procedure_encoder.rs:536:17
  20: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode
             at ./prusti-viper/src/encoder/procedure_encoder.rs:404:49
  21: prusti_viper::encoder::encoder::Encoder::encode_procedure
             at ./prusti-viper/src/encoder/encoder.rs:794:36
  22: prusti_viper::encoder::encoder::Encoder::process_encoding_queue
             at ./prusti-viper/src/encoder/encoder.rs:1535:41
  23: prusti_viper::verifier::Verifier::verify
             at ./prusti-viper/src/verifier.rs:242:9
  24: prusti_driver::verifier::verify
             at ./prusti/src/verifier.rs:48:39
  25: <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis::{{closure}}
             at ./prusti/src/callbacks.rs:79:17
  26: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /rustc/d0695c9081b16077d0aed368bccaf437d77ff497/compiler/rustc_interface/src/passes.rs:755:42
  27: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /rustc/d0695c9081b16077d0aed368bccaf437d77ff497/compiler/rustc_middle/src/ty/context.rs:1733:50
  28: rustc_middle::ty::context::tls::set_tlv
             at /rustc/d0695c9081b16077d0aed368bccaf437d77ff497/compiler/rustc_middle/src/ty/context.rs:1717:9
  29: rustc_middle::ty::context::tls::enter_context
             at /rustc/d0695c9081b16077d0aed368bccaf437d77ff497/compiler/rustc_middle/src/ty/context.rs:1733:9
  30: rustc_interface::passes::QueryContext::enter
             at /rustc/d0695c9081b16077d0aed368bccaf437d77ff497/compiler/rustc_interface/src/passes.rs:755:9
  31: <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis
             at ./prusti/src/callbacks.rs:40:9
  32: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  33: rustc_span::with_source_map
  34: rustc_interface::interface::create_compiler_and_run
  35: scoped_tls::ScopedKey<T>::set
```
</details>

**Comment by fpoli** [comment]
The bug seems to be in the equality `result == None`. A workaround:
```rust
use prusti_contracts::*;
use std::collections::HashMap;

#[extern_spec]
impl<T> Option<T> {
    #[pure]
    #[ensures(result == matches!(self, None))]
    pub fn is_none(&self) -> bool;
}

#[extern_spec]
impl HashMap<u64, u64> {
    #[pure]
    pub fn len(&self) -> usize;

    #[ensures(result.is_none() ==> self.len() == old(self.len()) + 1)]
    pub fn insert(&mut self, key: u64, value: u64) -> Option<u64>;
}

fn test(mut x: HashMap<u64, u64>) {
    let orig_len = x.len();
    if let None = x.insert(234, 345) {
        assert!(x.len() == orig_len + 1);
    }
}

fn main() {}
```

**Comment by fpoli** [comment]
@Aurel300 I think snapshots would also solve this issue.
