### ISSUE TITLE
Derived trait implementations can cause verification failures

### ISSUE THREAD

**Issue by zgrannan** [viperproject/prusti-dev#619]
To demonstrate the basic issue, verification of the following code:

```rust
#[derive(Debug)]
pub struct Foo { pub bar: i32 }

fn main() {}
```
fails with an error:
```
> prusti-rustc DeriveDebug.rs -Zmacro-backtrace


Verification of 2 items...
error: [Prusti: unsupported feature] cast statements that create loans are not supported
   --> DeriveDebug.rs:2:18
    |
1   |   #[derive(Debug)]
    |            ----- in this macro invocation
2   |   pub struct Foo { pub bar: i32 }
    |                    ^^^^^^^^^^^^
    | 
   ::: /nix/store/xdpqs7gp0dgml6j7nhja6hw24785p7jr-rust-1.55.0-nightly-2021-07-15/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:618:5
    |
618 | /     pub macro Debug($item:item) {
619 | |         /* compiler built-in */
620 | |     }
    | |_____- in this expansion of `#[derive(Debug)]`
```

This issue occurs with rust builtin macros as above, or macros from other crates. It seems reasonable, as I guess the macro expansion includes unsupported features.

As a Prusti user it seems like the way to address this would be to create a new macro without the unsupported feature. That could be undesirable since the user likely didn't originally author the macro or care to prove it's correctness. Perhaps there could be a way to have prusti not verify the implementation generated by the macro?

The codebase I'm trying to verify right now relies a lot on similar macro implementations, and I'd prefer to be able to simply ignore the macro-generated implementations from the verification scope.

**Comment by zgrannan** [comment]
In particular, for `Debug`, the macro-expansion generates:

```rust
#![feature(prelude_import)]
#![no_std]
#[prelude_import]
use ::std::prelude::rust_2015::*;
#[macro_use]
extern crate std;
pub struct Foo {
    pub bar: i32,
}
#[automatically_derived]
#[allow(unused_qualifications)]
impl ::core::fmt::Debug for Foo {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        match *self {
            Foo { bar: ref __self_0_0 } => {
                let debug_trait_builder =
                    &mut ::core::fmt::Formatter::debug_struct(f, "Foo");
                let _ =
                    ::core::fmt::DebugStruct::field(debug_trait_builder,
                                                    "bar", &&(*__self_0_0));
                ::core::fmt::DebugStruct::finish(debug_trait_builder)
            }
        }
    }
}
fn main() { }
```
 with the Prusti result:
```
error: [Prusti: unsupported feature] cast statements that create loans are not supported
  --> test2.rs:20:60
   |
20 | ...                   "bar", &&(*__self_0_0));
```

The reason for this error is that the argument is implicitly cast to `&dyn Debug`.

A similar example for enums:
```
#[derive(Debug)]
pub enum Foo { Bar, Baz }

fn main() {}
```
yields the error:
```
error: [Prusti: unsupported feature] the encoding of this reference copy has not been implemented
 --> test.rs:1:10
  |
1 | #[derive(Debug)]
  |          ^^^^^
  |
```

**Comment by Pointerbender** [comment]
This also seems to happen when deriving the Copy trait:
```rust
#[derive(Clone,Copy)]
pub enum Test {
    Test,
}
```

This yields the error:

```
thread 'rustc' panicked at 'assertion failed: self.is_struct() || self.is_union()', compiler/rustc_middle/src/ty/mod.rs:2439:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe1bf8e05c39bdcc73fc09e246b7209444e389bc/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/fe1bf8e05c39bdcc73fc09e246b7209444e389bc/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/fe1bf8e05c39bdcc73fc09e246b7209444e389bc/library/core/src/panicking.rs:50:5
   3: rustc_middle::ty::AdtDef::non_enum_variant
   4: prusti_viper::encoder::memory_eq_encoder::MemoryEqEncoder::encode_memory_eq_func_app
   5: prusti_viper::encoder::encoder::Encoder::encode_memory_eq_func_app
   6: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_assign_operand
   7: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_statement
   8: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_statement_at
   9: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_blocks_group
  10: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode
  11: prusti_viper::encoder::encoder::Encoder::encode_procedure
  12: prusti_viper::encoder::encoder::Encoder::process_encoding_queue
  13: prusti_viper::verifier::Verifier::verify
  14: prusti_driver::verifier::verify
  15: <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis
  16: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  17: rustc_span::with_source_map
  18: rustc_interface::interface::create_compiler_and_run
  19: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new

note: Prusti version: {commit 87cf7ac 2021-03-01 12:00:52 UTC, built on 2021-03-01 12:07:34 UTC}

query stack during panic:
end of query stack
```

Note that it works fine when only deriving `Clone` and not `Copy`. This also seems to work fine:

```rust
#[derive(Clone)]
pub enum Test {
    Test,
}

impl Copy for Test {}
```

EDIT October 12th 2021: on the latest master branch this is no longer a problem for the `Copy` trait, but it is still happening for the `Debug` trait.
