### ISSUE TITLE
Nondeterministic panic in mir_storage.rs

### ISSUE THREAD

**Issue by hkalbasi** [viperproject/prusti-dev#761]
I just tried the max example in [the tutorial](https://viperproject.github.io/prusti-dev/user-guide/basic.html) and received this error:
```
Unable to open 'prusti': File is a directory.
```

I'm on Pop OS (Ubuntu) 21.04 and VSCodium 1.61

Additional logs:

```
Activate Prusti Assistant
Checking Prusti prerequisites...
Checking Java home...
Checking Rustup and Cargo...
Run command 'rustup --version'
Spawned PID: 544054
Run command 'cargo --version'
Spawned PID: 544061
Checking Java...
Run command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java -version'
Spawned PID: 544063
Prerequisites are satisfied.
Check the Prusti dependencies...
Installing Prusti dependencies...
Using Prusti at Location(/home/hamid/.config/VSCodium/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti)
Checking rust toolchain version and components...
Run command 'rustup show'
Spawned PID: 544080
Prusti server is listening on port 45281.
Checking Prusti dependencies...
Checking Z3...
Run command '/home/hamid/.config/VSCodium/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/viper_tools/z3/bin/z3 --version'
Spawned PID: 544102
Checking Prusti...
Run command '/home/hamid/.config/VSCodium/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/prusti-rustc --version'
Spawned PID: 544103
Checking Cargo-Prusti...
Run command '/home/hamid/.config/VSCodium/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/cargo-prusti --help'
Spawned PID: 544124
Prusti checks completed.
Checking for updates...
Prusti is up-to-date.
The extension is now active.
Run verification on /home/hamid/Desktop/prusti/src/main.rs...
Preparing verification run #1.
Killing 0 processes.
Run command '/home/hamid/.config/VSCodium/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/cargo-prusti --message-format=json'
Spawned PID: 544184
Run verification on /home/hamid/Desktop/prusti/src/main.rs...
Preparing verification run #2.
Killing 0 processes.
Run command '/home/hamid/.config/VSCodium/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/cargo-prusti --message-format=json'
Spawned PID: 544459
Run verification on /home/hamid/Desktop/prusti/src/main.rs...
Preparing verification run #3.
Killing 0 processes.
Run command '/home/hamid/.config/VSCodium/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/cargo-prusti --message-format=json'
Spawned PID: 544699
Run verification on /home/hamid/Desktop/prusti/src/main.rs...
Preparing verification run #4.
Killing 0 processes.
Run command '/home/hamid/.config/VSCodium/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/cargo-prusti --message-format=json'
Spawned PID: 544878
Run verification on /home/hamid/Desktop/prusti/src/main.rs...
Preparing verification run #5.
Killing 0 processes.
Run command '/home/hamid/.config/VSCodium/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/cargo-prusti --message-format=json'
Spawned PID: 545057
Run verification on /home/hamid/Desktop/prusti/src/main.rs...
Preparing verification run #6.
Killing 0 processes.
Run command '/home/hamid/.config/VSCodium/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/cargo-prusti --message-format=json'
Spawned PID: 545145
```

**Comment by fpoli** [comment]
Hi, thank you for the report! Could you also attach the log from the "Prusti Assistant Trace" output tab?

My guess is that your `prusti` crate in which you wrote `main.rs` somehow conflicts with the `prusti` crate that we used to implement Prusti. Could you try renaming `/home/hamid/Desktop/prusti` (and the crate name in `/home/hamid/Desktop/prusti/Cargo.toml`) to something different?

**Comment by hkalbasi** [comment]
That's it. And just changing the Cargo.toml is enough. Thanks! 

I will close this issue, but detecting crate name for this kind of conflicts would be good.

**Comment by fpoli** [comment]
It'd like to keep this open a bit longer. The question is: can `cargo clippy` be used to check local crates named `clippy`? If yes, we can do whatever they do to avoid the conflict. If no, we'll not fix this behavior.

**Comment by hkalbasi** [comment]
> can cargo clippy be used to check local crates named clippy?

I tried and it seems there is no problem.

**Comment by fpoli** [comment]
Thanks! Have you also tried running Prusti from the command line, to see if it's an issue in Prusti or in the IDE extension? That is, executing `/home/hamid/.config/VSCodium/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/cargo-prusti` from the folder of your crate?

**Comment by hkalbasi** [comment]
I got this from that command:
```
hamid@pop-os:~/Desktop/prusti$ /home/hamid/.config/VSCodium/User/globalStorage/viper-admin.prusti-assistant/prustiTools/LatestRelease/prusti/cargo-prusti
    Checking prusti v0.1.0 (/home/hamid/Desktop/prusti)
warning: function is never used: `max`
 --> src/main.rs:6:4
  |
6 | fn max(a: i32, b: i32) -> i32 {
  |    ^^^
  |
  = note: `#[warn(dead_code)]` on by default

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', prusti-interface/src/environment/mir_storage.rs:47:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new

note: Prusti version: commit f10c42e 2021-09-22 11:47:38 UTC, built on 2021-09-22 11:52:35 UTC

warning: `prusti` (bin "prusti") generated 1 warning
error: could not compile `prusti`; 1 warning emitted
```

It won't panic if I change the crate name.

**Comment by fpoli** [comment]
Mmm, strange. I tried verifying the `max` example in a crate named `prusti`, but I'm unable to reproduce the "Unable to open 'prusti': File is a directory." and the other errors that you reported. If it's easy for you, could you attack a zip of the exact crate that you are trying to verify? A Docker image to reproduce the issue would be even better, if possible.

**Comment by fpoli** [comment]
We never tested Prusti on Pop OS so far. Maybe that's relevant, but I can't guess what might go wrong.

**Comment by hkalbasi** [comment]
It seems it isn't related to the name, but if I change the crate name or remove the target folder, it may solve (or happen again). It is not deterministic (or I can guess it) but if I change the name sometimes, it will happen. And "unable to open prusti" isn't the main error, but it is what it print when I click on the error:

![image](https://user-images.githubusercontent.com/45197576/141795351-e5900e08-f91e-4d98-98d4-d6b8b038ae91.png)

As you see, error belongs to file Prusti in Desktop, which is a directory.

logs:

```
┌──── Begin stderr ────┐
    Checking prusti_sample v0.1.0 (/home/hamid/Desktop/prusti)
[2021-11-15T13:45:13Z INFO  prusti_driver] Prusti version: commit f10c42e 2021-09-22 11:47:38 UTC, built on 2021-09-22 11:52:35 UTC
[2021-11-15T13:45:13Z INFO  prusti_viper::verifier] Received 2 functions to be verified:
[2021-11-15T13:45:13Z INFO  prusti_common::stopwatch::log_level] [prusti-viper] Starting: encoding to Viper
[2021-11-15T13:45:13Z INFO  prusti_viper::verifier]  - main from src/main.rs:15:1: 15:10 (#0) (prusti_sample::main)
[2021-11-15T13:45:13Z INFO  prusti_viper::verifier]  - max from src/main.rs:6:1: 6:30 (#0) (prusti_sample::max)
[2021-11-15T13:45:13Z INFO  prusti_viper::encoder::encoder] Encoding: main from src/main.rs:15:1: 15:10 (#0) (prusti_sample::main)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', prusti-interface/src/environment/mir_storage.rs:47:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5ecc8ad8462574354a55162a0c16b10eb95e3e70/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/5ecc8ad8462574354a55162a0c16b10eb95e3e70/library/core/src/panicking.rs:103:14
   2: core::panicking::panic
             at /rustc/5ecc8ad8462574354a55162a0c16b10eb95e3e70/library/core/src/panicking.rs:50:5
   3: std::thread::local::LocalKey<T>::with
   4: prusti_interface::environment::Environment::local_mir
   5: prusti_viper::encoder::specs_closures_collector::SpecsClosuresCollector::collect
   6: prusti_viper::encoder::encoder::Encoder::encode_procedure
   7: prusti_viper::encoder::encoder::Encoder::process_encoding_queue
   8: prusti_viper::verifier::Verifier::verify
   9: rustc_interface::passes::QueryContext::enter
  10: <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis
  11: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  12: rustc_span::with_source_map
  13: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new

note: Prusti version: commit f10c42e 2021-09-22 11:47:38 UTC, built on 2021-09-22 11:52:35 UTC

query stack during panic:
end of query stack
[2021-11-15T13:45:13Z INFO  prusti_common::stopwatch::log_level] [prusti-viper] Completed: encoding to Viper (0.033 seconds)
error: could not compile `prusti_sample`; 2 warnings emitted

└──── End stderr ──────┘
```

**Comment by fpoli** [comment]
That's very useful, thank you! The "unable to open prusti" error is an issue of the IDE, I moved it [here](https://github.com/viperproject/prusti-assistant/issues/117). Prusti's panic in `mir_storage.rs` is an orthogonal issue.

**Comment by fpoli** [comment]
Could you try selecting `LatestDev` in the `buildChannel` setting of the Prusti Assistant extension? That way, the extension uses the latest Prusti from the `master` branch and not a version that we fixed in September.

**Comment by hkalbasi** [comment]
It seems it isn't happening again. I will reopen the issue if it happens again.

By the way dev version is considerably faster. Thanks for great work!
