### ISSUE TITLE
'index out of bounds' panic in prusti-viper/mir_encoder

### ISSUE THREAD

**Issue by nonetype** [viperproject/prusti-dev#833]
### Code
https://gist.github.com/nonetype/817435fbc5a562d61265a0d4cb3820b3

### Env
```sh
DUMP_VIPER_PROGRAM=true RUST_BACKTRACE=1 ~/prusti-dev/target/debug/cargo-prusti
```

### Log
```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', prusti-viper/src/encoder/mir_encoder/mod.rs:141:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/404c8471aba60c2d837fa728e7c729a0f52d5830/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/404c8471aba60c2d837fa728e7c729a0f52d5830/library/core/src/panicking.rs:107:14
   2: core::panicking::panic_bounds_check
             at /rustc/404c8471aba60c2d837fa728e7c729a0f52d5830/library/core/src/panicking.rs:75:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/404c8471aba60c2d837fa728e7c729a0f52d5830/library/core/src/slice/index.rs:189:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/404c8471aba60c2d837fa728e7c729a0f52d5830/library/core/src/slice/index.rs:15:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/404c8471aba60c2d837fa728e7c729a0f52d5830/library/alloc/src/vec/mod.rs:2528:9
   6: prusti_viper::encoder::mir_encoder::PlaceEncoder::encode_projection
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/encoder/mir_encoder/mod.rs:141:38
   7: prusti_viper::encoder::mir_encoder::PlaceEncoder::encode_projection
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/encoder/mir_encoder/mod.rs:95:58
   8: prusti_viper::encoder::mir_encoder::PlaceEncoder::encode_place
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/encoder/mir_encoder/mod.rs:73:9
   9: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_generic_place
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/encoder/procedure_encoder.rs:5110:53
  10: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_postcondition_expr
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/encoder/procedure_encoder.rs:3907:45
  11: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_impure_function_call
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/encoder/procedure_encoder.rs:3154:13
  12: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_terminator
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/encoder/procedure_encoder.rs:2388:37
  13: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_statement_at
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/encoder/procedure_encoder.rs:1088:13
  14: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_block_terminator
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/encoder/procedure_encoder.rs:1051:42
  15: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_block
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/encoder/procedure_encoder.rs:949:43
  16: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_blocks_group
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/encoder/procedure_encoder.rs:545:17
  17: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/encoder/procedure_encoder.rs:414:49
  18: prusti_viper::encoder::encoder::Encoder::encode_procedure
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/encoder/encoder.rs:570:36
  19: prusti_viper::encoder::encoder::Encoder::process_encoding_queue
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/encoder/encoder.rs:833:40
  20: prusti_viper::verifier::Verifier::verify
             at /home/user/hacking-lab/prusti-dev/prusti-viper/src/verifier.rs:247:9
  21: prusti_driver::verifier::verify
             at /home/user/hacking-lab/prusti-dev/prusti/src/verifier.rs:51:39
  22: <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis::{{closure}}
             at /home/user/hacking-lab/prusti-dev/prusti/src/callbacks.rs:109:17
  23: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /rustc/404c8471aba60c2d837fa728e7c729a0f52d5830/compiler/rustc_interface/src/passes.rs:821:42
  24: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /rustc/404c8471aba60c2d837fa728e7c729a0f52d5830/compiler/rustc_middle/src/ty/context.rs:1750:50
  25: rustc_middle::ty::context::tls::set_tlv
             at /rustc/404c8471aba60c2d837fa728e7c729a0f52d5830/compiler/rustc_middle/src/ty/context.rs:1734:9
  26: rustc_middle::ty::context::tls::enter_context
             at /rustc/404c8471aba60c2d837fa728e7c729a0f52d5830/compiler/rustc_middle/src/ty/context.rs:1750:9
  27: rustc_interface::passes::QueryContext::enter
             at /rustc/404c8471aba60c2d837fa728e7c729a0f52d5830/compiler/rustc_interface/src/passes.rs:821:9
  28: <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis
             at /home/user/hacking-lab/prusti-dev/prusti/src/callbacks.rs:71:9
  29: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  30: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  31: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new

note: Prusti version: commit 69325d35ec 2021-12-20 16:52:13 UTC, built on 2021-12-27 04:31:16 UTC

query stack during panic:
end of query stack
```

https://github.com/viperproject/prusti-dev/blob/9aa65f8ec43c7699fa1c6e2f98ecd745634d490a/prusti-viper/src/encoder/mir_encoder/mod.rs#L139

**Comment by vakaras** [comment]
The example uses unsupported features like closures (the PR is still not merged) and bit operations (`payload ^= otp;`). However, Prusti should report a user-friendly error message instead of crashing.

Thank you for reporting this!
