### ISSUE TITLE
Failed initial build

### ISSUE THREAD

**Issue by jaybosamiya** [viperproject/prusti-dev#9]
When doing a `make build`, the build does not succeed due to `Error: no class 'viper.silver.ast.NamedDomainAxiom'`.

I am running the build on Ubuntu 16.04 (as described in the README), with all requirements and build steps mentioned inthe README being satisfied.

Any suggestions on how to fix this?

<details><summary>Click to expand the full build output</summary>

<p></p>

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/fpoli/compiletest-rs.git`
 Downloading log v0.4.5
 Downloading jni v0.11.0
 Downloading uuid v0.7.1
 Downloading error-chain v0.12.0
 Downloading cfg-if v0.1.5
 Downloading combine v3.5.2
 Downloading cesu8 v1.1.0
 Downloading jni-sys v0.3.0
 Downloading backtrace v0.3.9
 Downloading backtrace-sys v0.1.24
 Downloading libc v0.2.43
 Downloading rustc-demangle v0.1.9
 Downloading cc v1.0.25
 Downloading byteorder v1.2.6
 Downloading memchr v2.1.0
 Downloading unreachable v1.0.0
 Downloading ascii v0.7.1
 Downloading either v1.5.0
 Downloading version_check v0.1.4
 Downloading void v1.0.2
 Downloading walkdir v2.2.5
 Downloading same-file v1.0.3
 Downloading rand v0.5.5
 Downloading rand_core v0.2.1
 Downloading env_logger v0.5.13
 Downloading humantime v1.1.1
 Downloading atty v0.2.11
 Downloading termcolor v1.0.4
 Downloading regex v1.0.5
 Downloading quick-error v1.2.2
 Downloading utf8-ranges v1.0.1
 Downloading thread_local v0.3.6
 Downloading aho-corasick v0.6.8
 Downloading regex-syntax v0.6.2
 Downloading lazy_static v1.1.0
 Downloading ucd-util v0.1.1
 Downloading reqwest v0.9.2
 Downloading tempdir v0.3.7
 Downloading tokio v0.1.8
 Downloading serde_urlencoded v0.5.3
 Downloading mime v0.3.9
 Downloading encoding_rs v0.8.6
 Downloading mime_guess v2.0.0-alpha.6
 Downloading native-tls v0.2.1
 Downloading base64 v0.9.3
 Downloading serde_json v1.0.32
 Downloading serde v1.0.80
 Downloading futures v0.1.24
 Downloading tokio-io v0.1.8
 Downloading http v0.1.13
 Downloading libflate v0.1.18
 Downloading url v1.7.1
 Downloading hyper v0.12.11
 Downloading bytes v0.4.10
 Downloading hyper-tls v0.3.0
 Downloading tokio-codec v0.1.0
 Downloading tokio-current-thread v0.1.1
 Downloading tokio-uds v0.2.1
 Downloading mio v0.6.16
 Downloading tokio-udp v0.1.2
 Downloading tokio-executor v0.1.4
 Downloading tokio-timer v0.2.6
 Downloading tokio-threadpool v0.1.6
 Downloading tokio-tcp v0.1.1
 Downloading tokio-reactor v0.1.5
 Downloading tokio-fs v0.1.3
 Downloading iovec v0.1.2
 Downloading mio-uds v0.6.7
 Downloading slab v0.4.1
 Downloading net2 v0.2.33
 Downloading lazycell v1.2.0
 Downloading parking_lot v0.6.4
 Downloading num_cpus v1.8.0
 Downloading crossbeam-utils v0.5.0
 Downloading lock_api v0.1.3
 Downloading parking_lot_core v0.3.1
 Downloading owning_ref v0.3.3
 Downloading scopeguard v0.3.3
 Downloading stable_deref_trait v1.1.1
 Downloading smallvec v0.6.5
 Downloading rustc_version v0.2.3
 Downloading semver v0.9.0
 Downloading semver-parser v0.7.0
 Downloading crossbeam-deque v0.6.1
 Downloading crossbeam-epoch v0.5.2
 Downloading arrayvec v0.4.7
 Downloading memoffset v0.2.1
 Downloading nodrop v0.1.12
 Downloading itoa v0.4.3
 Downloading dtoa v0.4.3
 Downloading idna v0.1.5
 Downloading matches v0.1.8
 Downloading percent-encoding v1.0.1
 Downloading unicode-bidi v0.3.4
 Downloading unicode-normalization v0.1.7
 Downloading unicase v2.1.0
 Downloading unicase v1.4.2
 Downloading phf v0.7.23
 Downloading phf_shared v0.7.23
 Downloading siphasher v0.2.3
 Downloading phf_codegen v0.7.23
 Downloading phf_generator v0.7.23
 Downloading openssl v0.10.12
 Downloading openssl-sys v0.9.36
 Downloading openssl-probe v0.1.2
 Downloading foreign-types v0.3.2
 Downloading bitflags v1.0.4
 Downloading foreign-types-shared v0.1.1
 Downloading pkg-config v0.3.14
 Downloading safemem v0.3.0
 Downloading ryu v0.2.6
 Downloading fnv v1.0.6
 Downloading adler32 v1.0.3
 Downloading crc v1.8.1
 Downloading build_const v0.2.1
 Downloading h2 v0.1.12
 Downloading httparse v1.3.2
 Downloading want v0.0.6
 Downloading futures-cpupool v0.1.8
 Downloading time v0.1.40
 Downloading indexmap v1.0.1
 Downloading string v0.1.1
 Downloading try-lock v0.2.2
 Downloading rand v0.4.3
 Downloading remove_dir_all v0.5.1
 Downloading polonius-engine v0.5.0
 Downloading serde_derive v1.0.80
 Downloading csv v1.0.1
 Downloading polonius v0.2.0
 Downloading config v0.9.1
 Downloading rustc-hash v1.0.1
 Downloading datafrog v0.1.0
 Downloading quote v0.6.8
 Downloading syn v0.15.4
 Downloading proc-macro2 v0.4.19
 Downloading unicode-xid v0.1.0
 Downloading csv-core v0.1.4
 Downloading histo v0.1.0
 Downloading clap v2.32.0
 Downloading failure v0.1.2
 Downloading polonius-parser v0.1.0
 Downloading structopt v0.2.10
 Downloading streaming-stats v0.1.29
 Downloading num-traits v0.2.6
 Downloading strsim v0.7.0
 Downloading ansi_term v0.11.0
 Downloading textwrap v0.10.0
 Downloading vec_map v0.8.1
 Downloading unicode-width v0.1.5
 Downloading failure_derive v0.1.2
 Downloading syn v0.14.9
 Downloading synstructure v0.9.0
 Downloading lalrpop-util v0.15.2
 Downloading lalrpop v0.15.2
 Downloading regex-syntax v0.4.2
 Downloading regex v0.2.11
 Downloading digest v0.7.5
 Downloading diff v0.1.11
 Downloading string_cache v0.7.3
 Downloading atty v0.1.2
 Downloading ascii-canvas v1.0.0
 Downloading ena v0.5.0
 Downloading sha2 v0.7.1
 Downloading term v0.4.6
 Downloading bit-set v0.4.0
 Downloading docopt v0.8.3
 Downloading itertools v0.7.8
 Downloading petgraph v0.4.13
 Downloading regex-syntax v0.5.6
 Downloading generic-array v0.9.0
 Downloading typenum v1.10.0
 Downloading string_cache_shared v0.3.0
 Downloading precomputed-hash v0.1.1
 Downloading new_debug_unreachable v1.0.1
 Downloading string_cache_codegen v0.4.1
 Downloading quote v0.5.2
 Downloading proc-macro2 v0.3.8
 Downloading winapi v0.2.8
 Downloading kernel32-sys v0.2.2
 Downloading winapi-build v0.1.1
 Downloading block-buffer v0.3.3
 Downloading fake-simd v0.1.2
 Downloading byte-tools v0.2.0
 Downloading arrayref v0.3.5
 Downloading bit-vec v0.4.4
 Downloading strsim v0.6.0
 Downloading fixedbitset v0.1.9
 Downloading ordermap v0.3.5
 Downloading lalrpop-snap v0.15.2
 Downloading structopt-derive v0.2.10
 Downloading yaml-rust v0.4.2
 Downloading nom v4.0.0
 Downloading rust-ini v0.12.2
 Downloading toml v0.4.7
 Downloading serde-hjson v0.8.1
 Downloading linked-hash-map v0.5.1
 Downloading regex v0.1.80
 Downloading serde v0.8.23
 Downloading linked-hash-map v0.3.0
 Downloading lazy_static v0.2.11
 Downloading num-traits v0.1.43
 Downloading aho-corasick v0.5.3
 Downloading utf8-ranges v0.1.3
 Downloading memchr v0.1.11
 Downloading regex-syntax v0.3.9
 Downloading thread_local v0.2.7
 Downloading thread-id v2.0.0
 Downloading serde_test v0.8.23
 Downloading num-rational v0.2.1
 Downloading pretty_assertions v0.5.1
 Downloading num-integer v0.1.39
 Downloading num-bigint v0.2.0
 Downloading difference v2.0.0
 Downloading chrono v0.4.6
   Compiling version_check v0.1.4
   Compiling siphasher v0.2.3
   Compiling semver-parser v0.7.0
   Compiling unicode-xid v0.1.0
   Compiling libc v0.2.43
   Compiling rand_core v0.2.1
   Compiling void v1.0.2
   Compiling string_cache_shared v0.3.0
   Compiling winapi-build v0.1.1
   Compiling nodrop v0.1.12
   Compiling cfg-if v0.1.5
   Compiling proc-macro2 v0.4.19
   Compiling serde v1.0.80
   Compiling stable_deref_trait v1.1.1
   Compiling regex v0.2.11
   Compiling ucd-util v0.1.1
   Compiling byteorder v1.2.6
   Compiling typenum v1.10.0
   Compiling memoffset v0.2.1
   Compiling winapi v0.2.8
   Compiling crossbeam-utils v0.5.0
   Compiling scopeguard v0.3.3
   Compiling bit-vec v0.4.4
   Compiling either v1.5.0
   Compiling lazycell v1.2.0
   Compiling slab v0.4.1
   Compiling fixedbitset v0.1.9
   Compiling futures v0.1.24
   Compiling pkg-config v0.3.14
   Compiling term v0.4.6
   Compiling utf8-ranges v1.0.1
   Compiling cc v1.0.25
   Compiling ordermap v0.3.5
   Compiling precomputed-hash v0.1.1
   Compiling diff v0.1.11
   Compiling ena v0.5.0
   Compiling lalrpop-util v0.15.2
   Compiling regex-syntax v0.4.2
   Compiling matches v0.1.8
   Compiling build_const v0.2.1
   Compiling same-file v1.0.3
   Compiling foreign-types-shared v0.1.1
   Compiling byte-tools v0.2.0
   Compiling openssl v0.10.12
   Compiling arrayref v0.3.5
   Compiling fnv v1.0.6
   Compiling itoa v0.4.3
   Compiling httparse v1.3.2
   Compiling string v0.1.1
   Compiling fake-simd v0.1.2
   Compiling try-lock v0.2.2
   Compiling indexmap v1.0.1
   Compiling strsim v0.6.0
   Compiling native-tls v0.2.1
   Compiling rustc-demangle v0.1.9
   Compiling unicode-normalization v0.1.7
   Compiling bitflags v1.0.4
   Compiling ryu v0.2.6
   Compiling percent-encoding v1.0.1
   Compiling ascii v0.7.1
   Compiling num-traits v0.2.6
   Compiling openssl-probe v0.1.2
   Compiling regex v1.0.5
   Compiling unicode-width v0.1.5
   Compiling adler32 v1.0.3
   Compiling jni-sys v0.3.0
   Compiling cesu8 v1.1.0
   Compiling quick-error v1.2.2
   Compiling dtoa v0.4.3
   Compiling safemem v0.3.0
   Compiling failure_derive v0.1.2
   Compiling serde v0.8.23
   Compiling ansi_term v0.11.0
   Compiling strsim v0.7.0
   Compiling remove_dir_all v0.5.1
   Compiling vec_map v0.8.1
   Compiling utf8-ranges v0.1.3
   Compiling termcolor v1.0.4
   Compiling regex-syntax v0.3.9
   Compiling linked-hash-map v0.5.1
   Compiling datafrog v0.1.0
   Compiling num-integer v0.1.39
   Compiling lazy_static v0.2.11
   Compiling rust-ini v0.12.2
   Compiling num-bigint v0.2.0
   Compiling num-rational v0.2.1
   Compiling difference v2.0.0
   Compiling prusti-contracts v0.1.0 (file:///prusti-dev/prusti-contracts)
   Compiling proc-macro2 v0.3.8
   Compiling unicase v1.4.2
   Compiling memchr v2.1.0
   Compiling lazy_static v1.1.0
   Compiling unicase v2.1.0
   Compiling semver v0.9.0
   Compiling unreachable v1.0.0
   Compiling arrayvec v0.4.7
   Compiling log v0.4.5
   Compiling encoding_rs v0.8.6
   Compiling kernel32-sys v0.2.2
   Compiling rand v0.5.5
   Compiling iovec v0.1.2
   Compiling net2 v0.2.33
   Compiling num_cpus v1.8.0
   Compiling time v0.1.40
   Compiling memchr v0.1.11
   Compiling atty v0.2.11
   Compiling rand v0.4.3
   Compiling owning_ref v0.3.3
   Compiling regex-syntax v0.5.6
   Compiling regex-syntax v0.6.2
   Compiling rustc-hash v1.0.1
   Compiling itertools v0.7.8
   Compiling bit-set v0.4.0
   Compiling petgraph v0.4.13
   Compiling ascii-canvas v1.0.0
   Compiling tokio-executor v0.1.4
   Compiling openssl-sys v0.9.36
   Compiling backtrace-sys v0.1.24
   Compiling unicode-bidi v0.3.4
   Compiling crc v1.8.1
   Compiling foreign-types v0.3.2
   Compiling walkdir v2.2.5
   Compiling block-buffer v0.3.3
   Compiling textwrap v0.10.0
   Compiling humantime v1.1.1
   Compiling base64 v0.9.3
   Compiling yaml-rust v0.4.2
   Compiling serde_test v0.8.23
   Compiling pretty_assertions v0.5.1
   Compiling quote v0.5.2
   Compiling rustc_version v0.2.3
   Compiling smallvec v0.6.5
   Compiling new_debug_unreachable v1.0.1
   Compiling want v0.0.6
   Compiling bytes v0.4.10
   Compiling mio v0.6.16
   Compiling futures-cpupool v0.1.8
   Compiling uuid v0.7.1
   Compiling aho-corasick v0.5.3
   Compiling lock_api v0.1.3
   Compiling tempdir v0.3.7
   Compiling polonius-engine v0.5.0
   Compiling tokio-current-thread v0.1.1
   Compiling tokio-timer v0.2.6
   Compiling idna v0.1.5
   Compiling jni v0.11.0
   Compiling clap v2.32.0
   Compiling linked-hash-map v0.3.0
   Compiling parking_lot_core v0.3.1
   Compiling tokio-io v0.1.8
   Compiling http v0.1.13
   Compiling mio-uds v0.6.7
   Compiling generic-array v0.9.0
   Compiling quote v0.6.8
   Compiling url v1.7.1
   Compiling streaming-stats v0.1.29
   Compiling num-traits v0.1.43
   Compiling phf_shared v0.7.23
   Compiling thread_local v0.3.6
   Compiling crossbeam-epoch v0.5.2
   Compiling aho-corasick v0.6.8
   Compiling combine v3.5.2
   Compiling nom v4.0.0
   Compiling csv-core v0.1.4
   Compiling atty v0.1.2
   Compiling thread-id v2.0.0
   Compiling mime v0.3.9
   Compiling tokio-codec v0.1.0
   Compiling digest v0.7.5
   Compiling backtrace v0.3.9
   Compiling libflate v0.1.18
   Compiling syn v0.15.4
   Compiling syn v0.14.9
   Compiling serde_json v1.0.32
   Compiling toml v0.4.7
   Compiling histo v0.1.0
   Compiling phf_generator v0.7.23
   Compiling phf v0.7.23
   Compiling chrono v0.4.6
   Compiling crossbeam-deque v0.6.1
   Compiling serde_urlencoded v0.5.3
   Compiling h2 v0.1.12
   Compiling thread_local v0.2.7
   Compiling csv v1.0.1
   Compiling sha2 v0.7.1
   Compiling error-chain v0.12.0
   Compiling serde_derive v1.0.80
   Compiling synstructure v0.9.0
   Compiling structopt-derive v0.2.10
   Compiling string_cache_codegen v0.4.1
   Compiling phf_codegen v0.7.23
   Compiling prusti v0.1.0 (file:///prusti-dev/prusti)
   Compiling tokio-threadpool v0.1.6
   Compiling regex v0.1.80
   Compiling parking_lot v0.6.4
   Compiling env_logger v0.5.13
   Compiling string_cache v0.7.3
   Compiling mime_guess v2.0.0-alpha.6
   Compiling structopt v0.2.10
   Compiling tokio-fs v0.1.3
   Compiling tokio-reactor v0.1.5
   Compiling serde-hjson v0.8.1
   Compiling docopt v0.8.3
   Compiling jni-gen v0.1.0 (file:///prusti-dev/jni-gen)
   Compiling tokio-udp v0.1.2
   Compiling tokio-tcp v0.1.1
   Compiling tokio-uds v0.2.1
   Compiling failure v0.1.2
   Compiling config v0.9.1
   Compiling tokio v0.1.8
   Compiling lalrpop-snap v0.15.2
   Compiling hyper v0.12.11
   Compiling hyper-tls v0.3.0
   Compiling reqwest v0.9.2
   Compiling viper-sys v0.1.0 (file:///prusti-dev/viper-sys)
   Compiling systest v0.1.0 (file:///prusti-dev/jni-gen/systest)
error: failed to run custom build command for `viper-sys v0.1.0 (file:///prusti-dev/viper-sys)`
process didn't exit successfully: `/prusti-dev/target/debug/build/viper-sys-b2f7008154f8e25e/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-env-changed=VIPER_HOME
cargo:rerun-if-changed=/usr/lib/viper/
cargo:rerun-if-changed=/usr/lib/viper/viper.silicon-1.1-SNAPSHOT.jar
cargo:rerun-if-changed=/usr/lib/viper/com.typesafe.akka.akka-http-spray-json_2.12-10.1.8.jar
cargo:rerun-if-changed=/usr/lib/viper/com.typesafe.ssl-config-core_2.12-0.3.7.jar
cargo:rerun-if-changed=/usr/lib/viper/commons-io.commons-io-2.6.jar
cargo:rerun-if-changed=/usr/lib/viper/com.google.guava.guava-27.0-jre.jar
cargo:rerun-if-changed=/usr/lib/viper/com.typesafe.scala-logging.scala-logging_2.12-3.9.0.jar
cargo:rerun-if-changed=/usr/lib/viper/ch.qos.logback.logback-classic-1.2.3.jar
cargo:rerun-if-changed=/usr/lib/viper/ch.qos.logback.logback-core-1.2.3.jar
cargo:rerun-if-changed=/usr/lib/viper/org.scala-lang.scala-library-2.12.7.jar
cargo:rerun-if-changed=/usr/lib/viper/com.typesafe.config-1.3.3.jar
cargo:rerun-if-changed=/usr/lib/viper/com.typesafe.akka.akka-http-core_2.12-10.1.8.jar
cargo:rerun-if-changed=/usr/lib/viper/io.spray.spray-json_2.12-1.3.5.jar
cargo:rerun-if-changed=/usr/lib/viper/Alloy-5.0.0.1.jar
cargo:rerun-if-changed=/usr/lib/viper/com.typesafe.akka.akka-protobuf_2.12-2.5.22.jar
cargo:rerun-if-changed=/usr/lib/viper/com.lihaoyi.sourcecode_2.12-0.1.4.jar
cargo:rerun-if-changed=/usr/lib/viper/org.apache.commons.commons-pool2-2.6.0.jar
cargo:rerun-if-changed=/usr/lib/viper/org.scalactic.scalactic_2.12-3.0.5.jar
cargo:rerun-if-changed=/usr/lib/viper/com.typesafe.akka.akka-http_2.12-10.1.8.jar
cargo:rerun-if-changed=/usr/lib/viper/org.slf4j.slf4j-api-1.7.25.jar
cargo:rerun-if-changed=/usr/lib/viper/common.common-0.1.0-SNAPSHOT.jar
cargo:rerun-if-changed=/usr/lib/viper/com.lihaoyi.fastparse_2.12-1.0.0.jar
cargo:rerun-if-changed=/usr/lib/viper/com.google.guava.failureaccess-1.0.jar
cargo:rerun-if-changed=/usr/lib/viper/org.rogach.scallop_2.12-3.1.3.jar
cargo:rerun-if-changed=/usr/lib/viper/org.scala-lang.modules.scala-java8-compat_2.12-0.8.0.jar
cargo:rerun-if-changed=/usr/lib/viper/com.typesafe.akka.akka-stream_2.12-2.5.22.jar
cargo:rerun-if-changed=/usr/lib/viper/viper.silver-0.1-SNAPSHOT.jar
cargo:rerun-if-changed=/usr/lib/viper/com.google.errorprone.error_prone_annotations-2.2.0.jar
cargo:rerun-if-changed=/usr/lib/viper/org.scala-lang.modules.scala-parser-combinators_2.12-1.1.1.jar
cargo:rerun-if-changed=/usr/lib/viper/com.typesafe.akka.akka-parsing_2.12-10.1.8.jar
cargo:rerun-if-changed=/usr/lib/viper/org.scala-lang.scala-reflect-2.12.7.jar
cargo:rerun-if-changed=/usr/lib/viper/viper.viperserver-1.1-SNAPSHOT.jar
cargo:rerun-if-changed=/usr/lib/viper/com.lihaoyi.fastparse-utils_2.12-1.0.0.jar
cargo:rerun-if-changed=/usr/lib/viper/org.scala-lang.modules.scala-xml_2.12-1.0.6.jar
cargo:rerun-if-changed=/usr/lib/viper/com.typesafe.akka.akka-actor_2.12-2.5.22.jar
cargo:rerun-if-changed=/usr/lib/viper/org.jgrapht.jgrapht-core-1.2.0.jar
cargo:rerun-if-changed=/usr/lib/viper/com.google.j2objc.j2objc-annotations-1.1.jar
cargo:rerun-if-changed=/usr/lib/viper/org.codehaus.mojo.animal-sniffer-annotations-1.17.jar
cargo:rerun-if-changed=/usr/lib/viper/com.google.guava.listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
cargo:rerun-if-changed=/usr/lib/viper/org.reactivestreams.reactive-streams-1.0.2.jar
cargo:rerun-if-changed=/usr/lib/viper/viper.carbon-1.0-SNAPSHOT.jar

--- stderr
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: viper/silver/ast/NamedDomainAxiom
Caused by: java.lang.ClassNotFoundException: viper.silver.ast.NamedDomainAxiom
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
thread 'main' panicked at 'Error: no class 'viper.silver.ast.NamedDomainAxiom'
Caused by: Java exception was thrown
', viper-sys/build.rs:621:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```
</details>

**Comment by vakaras** [comment]
The Viper DEB packages build is broken and the packages are outdated. I will try to fix it.

**Comment by fpoli** [comment]
As a temporary workaround I think you can use a8d7ec491f1ff7c2c8d3181a1201f2d5c23694ff.

The `NamedDomainAxiom` class has been recently added to Viper, thus the latest Prusti version expects it, but that class for some reason is not yet in the DEB package.

**Comment by jaybosamiya** [comment]
Thanks @vakaras and @fpoli !

I was able to get it to build with the suggested commit https://github.com/viperproject/prusti-dev/commit/a8d7ec491f1ff7c2c8d3181a1201f2d5c23694ff.

**Comment by vakaras** [comment]
I have fixed the Viper DEB build, so it should work now. Please let us know if you have any further issues.

**Comment by jaybosamiya** [comment]
I can conform that it works on `master` now. Thanks @vakaras !
